# HRMS API

@baseUrl = http://localhost:8080/api/v1
@employeeId = 65f48728add77bdfb800f47c

### Create a new employee
POST {{baseUrl}}/employees
Content-Type: application/json

{
    "name": "John Doe",
    "salary": 1000,
    "age": 20
}

### Get all employees
GET {{baseUrl}}/employees

### Get employee by id
GET {{baseUrl}}/employees/{{employeeId}}

### Update an employee by id
PUT {{baseUrl}}/employees/{{employeeId}}
Content-Type: application/json

{
    "name": "John Doe",
    "salary": 2000,
    "age": 30
}

### Delete an employee by id
DELETE {{baseUrl}}/employees/{{employeeId}}
