# HRMS API

@baseUrl = http://localhost:8080/api/v1
@employeeId = "65f4862e4c874bbe7d9153ca"

### Create a new employee
POST {{baseUrl}}/employees
Content-Type: application/json

{
    "name": "John Doe",
    "salary": 1000,
    "age": 20
}

### Get all employees
GET {{baseUrl}}/employees

### Get employee by id
GET {{baseUrl}}/employees/{{employeeId}}