// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: legal_entity_snapshots.sql

package dbmodels

import (
	"context"

	"eats/backend/common"
	"eats/backend/common/shared"
)

const saveLegalEntitySnapshot = `-- name: SaveLegalEntitySnapshot :exec
INSERT INTO billing.legal_entity_snapshots (
    snapshot_uuid, name, address, tax_id
)
VALUES (
    $1, $2,
    $3, $4
)
`

type SaveLegalEntitySnapshotParams struct {
	SnapshotUuid common.UUID
	Name         string
	Address      shared.Address
	TaxID        *shared.TaxID
}

func (q *Queries) SaveLegalEntitySnapshot(ctx context.Context, arg SaveLegalEntitySnapshotParams) error {
	_, err := q.db.Exec(ctx, saveLegalEntitySnapshot,
		arg.SnapshotUuid,
		arg.Name,
		arg.Address,
		arg.TaxID,
	)
	return err
}
