// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbmodels

import (
	"eats/backend/billing/domain"
	"github.com/jackc/pgx/v5/pgtype"
)

type BillingDocument struct {
	DocumentUuid      domain.DocumentUUID
	ExternalReference *string
	DocumentNumber    string
	SeriesPrefix      string
}

type BillingDocumentSeries struct {
	Prefix     string
	LastNumber int32
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}
