// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"eats/backend/billing/domain"
	"eats/backend/common/shared"

	"github.com/oapi-codegen/runtime"
	"github.com/shopspring/decimal"
)

// Defines values for DocumentType.
const (
	Receipt DocumentType = "receipt"
)

// Defines values for TaxType.
const (
	Gst      TaxType = "gst"
	SalesTax TaxType = "sales-tax"
	Vat      TaxType = "vat"
)

// Address defines model for Address.
type Address struct {
	// City City name
	City string `json:"city"`

	// CountryCode ISO 3166-1 alpha-2 country code
	CountryCode shared.CountryCode `json:"country_code"`

	// Line1 First address line
	Line1 string `json:"line1"`

	// Line2 Second address line
	Line2 string `json:"line2"`

	// PostalCode Postal code
	PostalCode string `json:"postal_code"`
}

// CreateDocument defines model for CreateDocument.
type CreateDocument struct {
	Buyer LegalEntity `json:"buyer"`

	// Currency Currency code in ISO 4217 format
	Currency Currency `json:"currency"`

	// IssueDate Document issue date and time
	IssueDate time.Time `json:"issue_date"`

	// LineItems Document line items
	LineItems []LineItem  `json:"line_items"`
	Seller    LegalEntity `json:"seller"`
}

// Currency Currency code in ISO 4217 format
type Currency = shared.Currency

// Decimal defines model for Decimal.
type Decimal = decimal.Decimal

// DocumentResponse defines model for DocumentResponse.
type DocumentResponse struct {
	Buyer LegalEntity `json:"buyer"`

	// Currency Currency code in ISO 4217 format
	Currency Currency `json:"currency"`

	// DocumentNumber Human-readable document number
	DocumentNumber string `json:"document_number"`

	// DocumentType Type of the billing document
	DocumentType DocumentType          `json:"document_type"`
	IssueDate    time.Time             `json:"issue_date"`
	LineItems    []ResponseLineItem    `json:"line_items"`
	Seller       LegalEntity           `json:"seller"`
	Summary      PriceBreakdownSummary `json:"summary"`

	// Uuid UUID of a document
	Uuid DocumentUUID `json:"uuid"`
}

// DocumentType Type of the billing document
type DocumentType string

// DocumentUUID UUID of a document
type DocumentUUID = domain.DocumentUUID

// ErrorDetails defines model for ErrorDetails.
type ErrorDetails struct {
	EntityId   *string `json:"entity_id,omitempty"`
	EntityType *string `json:"entity_type,omitempty"`
	ErrorSlug  string  `json:"error_slug"`
	Message    string  `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Details Detailed error information
	Details []ErrorDetails `json:"details"`

	// Message Human-readable error message
	Message string `json:"message"`

	// Slug Error slug
	Slug string `json:"slug"`
}

// LegalEntity defines model for LegalEntity.
type LegalEntity struct {
	Address Address `json:"address"`

	// Name Legal entity name
	Name string `json:"name"`

	// TaxId Tax identification number
	TaxId *TaxID `json:"tax_id,omitempty"`
}

// LineItem defines model for LineItem.
type LineItem struct {
	IsGross      bool         `json:"is_gross"`
	LineItemType LineItemType `json:"line_item_type"`

	// Name Item description/name
	Name string `json:"name"`

	// Quantity Quantity of items
	Quantity   int     `json:"quantity"`
	UnitAmount Decimal `json:"unit_amount"`
}

// LineItemType defines model for LineItemType.
type LineItemType = shared.LineItemType

// PriceBreakdown defines model for PriceBreakdown.
type PriceBreakdown struct {
	GrossAmount Decimal `json:"gross_amount"`
	NetAmount   Decimal `json:"net_amount"`
	TaxAmount   Decimal `json:"tax_amount"`
	TaxRate     Decimal `json:"tax_rate"`

	// TaxType Type of tax applied
	TaxType         TaxType `json:"tax_type"`
	UnitGrossAmount Decimal `json:"unit_gross_amount"`
	UnitNetAmount   Decimal `json:"unit_net_amount"`
	UnitTaxAmount   Decimal `json:"unit_tax_amount"`
}

// PriceBreakdownSummary defines model for PriceBreakdownSummary.
type PriceBreakdownSummary struct {
	GrossAmount Decimal      `json:"gross_amount"`
	NetAmount   Decimal      `json:"net_amount"`
	TaxAmount   Decimal      `json:"tax_amount"`
	Taxes       []TaxSummary `json:"taxes"`
}

// ResponseLineItem defines model for ResponseLineItem.
type ResponseLineItem struct {
	Breakdown    PriceBreakdown `json:"breakdown"`
	LineItemType LineItemType   `json:"line_item_type"`
	Name         string         `json:"name"`
	Quantity     int            `json:"quantity"`
}

// TaxID Tax identification number
type TaxID = shared.TaxID

// TaxSummary defines model for TaxSummary.
type TaxSummary struct {
	NetAmount Decimal `json:"net_amount"`
	TaxAmount Decimal `json:"tax_amount"`
	TaxRate   Decimal `json:"tax_rate"`

	// TaxType Type of tax applied
	TaxType TaxType `json:"tax_type"`
}

// TaxType Type of tax applied
type TaxType string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// CreateReceiptJSONRequestBody defines body for CreateReceipt for application/json ContentType.
type CreateReceiptJSONRequestBody = CreateDocument

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// CreateReceiptWithBody request with any body
	CreateReceiptWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateReceipt(ctx context.Context, body CreateReceiptJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDocument request
	GetDocument(ctx context.Context, documentUuid DocumentUUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PrintDocument request
	PrintDocument(ctx context.Context, documentUuid DocumentUUID, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) CreateReceiptWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateReceiptRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateReceipt(ctx context.Context, body CreateReceiptJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateReceiptRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetDocument(ctx context.Context, documentUuid DocumentUUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDocumentRequest(c.Server, documentUuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PrintDocument(ctx context.Context, documentUuid DocumentUUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPrintDocumentRequest(c.Server, documentUuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewCreateReceiptRequest calls the generic CreateReceipt builder with application/json body
func NewCreateReceiptRequest(server string, body CreateReceiptJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateReceiptRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateReceiptRequestWithBody generates requests for CreateReceipt with any type of body
func NewCreateReceiptRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/billing/documents/receipt")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetDocumentRequest generates requests for GetDocument
func NewGetDocumentRequest(server string, documentUuid DocumentUUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "document_uuid", runtime.ParamLocationPath, documentUuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/billing/documents/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPrintDocumentRequest generates requests for PrintDocument
func NewPrintDocumentRequest(server string, documentUuid DocumentUUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "document_uuid", runtime.ParamLocationPath, documentUuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/billing/documents/%s/print", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// CreateReceiptWithBodyWithResponse request with any body
	CreateReceiptWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateReceiptResponse, error)

	CreateReceiptWithResponse(ctx context.Context, body CreateReceiptJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateReceiptResponse, error)

	// GetDocumentWithResponse request
	GetDocumentWithResponse(ctx context.Context, documentUuid DocumentUUID, reqEditors ...RequestEditorFn) (*GetDocumentResponse, error)

	// PrintDocumentWithResponse request
	PrintDocumentWithResponse(ctx context.Context, documentUuid DocumentUUID, reqEditors ...RequestEditorFn) (*PrintDocumentResponse, error)
}

type CreateReceiptResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *struct {
		// DocumentUuid UUID of a document
		DocumentUuid DocumentUUID `json:"document_uuid"`
	}
	JSON400 *BadRequest
	JSON401 *Unauthorized
}

// Status returns HTTPResponse.Status
func (r CreateReceiptResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateReceiptResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetDocumentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DocumentResponse
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON404      *NotFound
}

// Status returns HTTPResponse.Status
func (r GetDocumentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDocumentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PrintDocumentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON404      *NotFound
}

// Status returns HTTPResponse.Status
func (r PrintDocumentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PrintDocumentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// CreateReceiptWithBodyWithResponse request with arbitrary body returning *CreateReceiptResponse
func (c *ClientWithResponses) CreateReceiptWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateReceiptResponse, error) {
	rsp, err := c.CreateReceiptWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateReceiptResponse(rsp)
}

func (c *ClientWithResponses) CreateReceiptWithResponse(ctx context.Context, body CreateReceiptJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateReceiptResponse, error) {
	rsp, err := c.CreateReceipt(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateReceiptResponse(rsp)
}

// GetDocumentWithResponse request returning *GetDocumentResponse
func (c *ClientWithResponses) GetDocumentWithResponse(ctx context.Context, documentUuid DocumentUUID, reqEditors ...RequestEditorFn) (*GetDocumentResponse, error) {
	rsp, err := c.GetDocument(ctx, documentUuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDocumentResponse(rsp)
}

// PrintDocumentWithResponse request returning *PrintDocumentResponse
func (c *ClientWithResponses) PrintDocumentWithResponse(ctx context.Context, documentUuid DocumentUUID, reqEditors ...RequestEditorFn) (*PrintDocumentResponse, error) {
	rsp, err := c.PrintDocument(ctx, documentUuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePrintDocumentResponse(rsp)
}

// ParseCreateReceiptResponse parses an HTTP response from a CreateReceiptWithResponse call
func ParseCreateReceiptResponse(rsp *http.Response) (*CreateReceiptResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateReceiptResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest struct {
			// DocumentUuid UUID of a document
			DocumentUuid DocumentUUID `json:"document_uuid"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseGetDocumentResponse parses an HTTP response from a GetDocumentWithResponse call
func ParseGetDocumentResponse(rsp *http.Response) (*GetDocumentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDocumentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DocumentResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParsePrintDocumentResponse parses an HTTP response from a PrintDocumentWithResponse call
func ParsePrintDocumentResponse(rsp *http.Response) (*PrintDocumentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PrintDocumentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}
