// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers.sql

package dbmodels

import (
	"context"

	"eats/backend/common/shared"
	"eats/backend/orders/app"
)

const getCustomerByUUID = `-- name: GetCustomerByUUID :one
SELECT
	customer_uuid, name, email, address, phone_number
FROM
	orders.customers
WHERE
	customer_uuid = $1
`

func (q *Queries) GetCustomerByUUID(ctx context.Context, customerUuid app.CustomerUUID) (OrdersCustomer, error) {
	row := q.db.QueryRow(ctx, getCustomerByUUID, customerUuid)
	var i OrdersCustomer
	err := row.Scan(
		&i.CustomerUuid,
		&i.Name,
		&i.Email,
		&i.Address,
		&i.PhoneNumber,
	)
	return i, err
}

const insertCustomer = `-- name: InsertCustomer :exec
INSERT INTO
	orders.customers (
	customer_uuid,
	name,
	email,
	address,
	phone_number)
VALUES
	($1, $2, $3, $4, $5)
`

type InsertCustomerParams struct {
	CustomerUuid app.CustomerUUID
	Name         string
	Email        string
	Address      shared.Address
	PhoneNumber  string
}

func (q *Queries) InsertCustomer(ctx context.Context, arg InsertCustomerParams) error {
	_, err := q.db.Exec(ctx, insertCustomer,
		arg.CustomerUuid,
		arg.Name,
		arg.Email,
		arg.Address,
		arg.PhoneNumber,
	)
	return err
}
