// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbmodels

import (
	"database/sql/driver"
	"fmt"
	"time"

	"eats/backend/common"
	"eats/backend/common/shared"
	"eats/backend/orders/app"
	"github.com/shopspring/decimal"
)

type OrdersItemCategory string

const (
	OrdersItemCategoryFood     OrdersItemCategory = "food"
	OrdersItemCategoryBeverage OrdersItemCategory = "beverage"
)

func (e *OrdersItemCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrdersItemCategory(s)
	case string:
		*e = OrdersItemCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for OrdersItemCategory: %T", src)
	}
	return nil
}

type NullOrdersItemCategory struct {
	OrdersItemCategory OrdersItemCategory
	Valid              bool // Valid is true if OrdersItemCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrdersItemCategory) Scan(value interface{}) error {
	if value == nil {
		ns.OrdersItemCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrdersItemCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrdersItemCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrdersItemCategory), nil
}

type OrdersCourier struct {
	CourierUuid app.CourierUUID
	Name        string
	PhoneNumber string
	City        string
}

type OrdersCustomer struct {
	CustomerUuid app.CustomerUUID
	Name         string
	Email        string
	Address      shared.Address
	PhoneNumber  string
}

type OrdersOrder struct {
	OrderUuid             app.OrderUUID
	QuoteUuid             app.QuoteUUID
	CustomerUuid          app.CustomerUUID
	RestaurantUuid        app.RestaurantUUID
	CourierUuid           *app.CourierUUID
	DeliveryAddress       shared.Address
	OrderedAt             time.Time
	RestaurantConfirmedAt *time.Time
	CourierAcceptedAt     *time.Time
	RestaurantPreparedAt  *time.Time
	PickedUpAt            *time.Time
	DeliveredAt           *time.Time
	ItemsSubtotalGross    decimal.Decimal
	ServiceFeeGross       decimal.Decimal
	DeliveryFeeGross      decimal.Decimal
	TotalAmountGross      decimal.Decimal
	TotalTax              decimal.Decimal
	Currency              shared.Currency
}

type OrdersQuote struct {
	QuoteUuid          app.QuoteUUID
	CustomerUuid       app.CustomerUUID
	RestaurantUuid     app.RestaurantUUID
	DeliveryAddress    shared.Address
	CreatedAt          time.Time
	ItemsSubtotalGross decimal.Decimal
	ServiceFeeGross    decimal.Decimal
	DeliveryFeeGross   decimal.Decimal
	TotalAmountGross   decimal.Decimal
	TotalTax           decimal.Decimal
	Currency           shared.Currency
}

type OrdersQuoteItem struct {
	QuoteItemUuid common.UUID
	QuoteUuid     app.QuoteUUID
	MenuItemUuid  app.RestaurantMenuItemUUID
	GrossPrice    decimal.Decimal
	Quantity      int32
}

type OrdersRestaurant struct {
	RestaurantUuid app.RestaurantUUID
	Name           string
	Description    string
	Address        shared.Address
	Currency       shared.Currency
}

type OrdersRestaurantMenuItem struct {
	RestaurantMenuItemUuid app.RestaurantMenuItemUUID
	RestaurantUuid         app.RestaurantUUID
	Name                   string
	GrossPrice             decimal.Decimal
	Ordering               float64
	IsArchived             bool
	Category               app.ItemCategory
}
