// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbmodels

import (
	"time"

	"eats/backend/common"
	"eats/backend/common/shared"
	"eats/backend/orders/app"
	"github.com/shopspring/decimal"
)

type OrdersCustomer struct {
	CustomerUuid app.CustomerUUID
	Name         string
	Email        string
	Address      shared.Address
	PhoneNumber  string
}

type OrdersQuote struct {
	QuoteUuid          app.QuoteUUID
	CustomerUuid       app.CustomerUUID
	RestaurantUuid     app.RestaurantUUID
	DeliveryAddress    shared.Address
	CreatedAt          time.Time
	ItemsSubtotalGross decimal.Decimal
	ServiceFeeGross    decimal.Decimal
	DeliveryFeeGross   decimal.Decimal
	TotalAmountGross   decimal.Decimal
	TotalTax           decimal.Decimal
	Currency           shared.Currency
}

type OrdersQuoteItem struct {
	QuoteItemUuid common.UUID
	QuoteUuid     app.QuoteUUID
	MenuItemUuid  app.RestaurantMenuItemUUID
	GrossPrice    decimal.Decimal
	Quantity      int32
}

type OrdersRestaurant struct {
	RestaurantUuid app.RestaurantUUID
	Name           string
	Description    string
	Address        shared.Address
	Currency       shared.Currency
}

type OrdersRestaurantMenuItem struct {
	RestaurantMenuItemUuid app.RestaurantMenuItemUUID
	RestaurantUuid         app.RestaurantUUID
	Name                   string
	GrossPrice             decimal.Decimal
	Ordering               float64
	IsArchived             bool
}
