// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package dbmodels

import (
	"context"
	"time"

	"eats/backend/common"
	"eats/backend/common/shared"
	"eats/backend/orders/app"
	"github.com/shopspring/decimal"
)

const addQuote = `-- name: AddQuote :exec
INSERT INTO orders.quotes (
	quote_uuid,
	customer_uuid,
	restaurant_uuid,
	delivery_address,
	items_subtotal_gross,
	service_fee_gross,
	delivery_fee_gross,
	total_amount_gross,
	total_tax,
	created_at,
	currency
)
VALUES
	($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type AddQuoteParams struct {
	QuoteUuid          app.QuoteUUID
	CustomerUuid       app.CustomerUUID
	RestaurantUuid     app.RestaurantUUID
	DeliveryAddress    shared.Address
	ItemsSubtotalGross decimal.Decimal
	ServiceFeeGross    decimal.Decimal
	DeliveryFeeGross   decimal.Decimal
	TotalAmountGross   decimal.Decimal
	TotalTax           decimal.Decimal
	CreatedAt          time.Time
	Currency           shared.Currency
}

func (q *Queries) AddQuote(ctx context.Context, arg AddQuoteParams) error {
	_, err := q.db.Exec(ctx, addQuote,
		arg.QuoteUuid,
		arg.CustomerUuid,
		arg.RestaurantUuid,
		arg.DeliveryAddress,
		arg.ItemsSubtotalGross,
		arg.ServiceFeeGross,
		arg.DeliveryFeeGross,
		arg.TotalAmountGross,
		arg.TotalTax,
		arg.CreatedAt,
		arg.Currency,
	)
	return err
}

type AddQuoteItemsParams struct {
	QuoteItemUuid common.UUID
	QuoteUuid     app.QuoteUUID
	MenuItemUuid  app.RestaurantMenuItemUUID
	GrossPrice    decimal.Decimal
	Quantity      int32
}

const getQuote = `-- name: GetQuote :one
SELECT
	quote_uuid, customer_uuid, restaurant_uuid, delivery_address, created_at, items_subtotal_gross, service_fee_gross, delivery_fee_gross, total_amount_gross, total_tax, currency
FROM
	orders.quotes AS quotes
WHERE
	quote_uuid = $1
LIMIT 1
`

func (q *Queries) GetQuote(ctx context.Context, quoteUuid app.QuoteUUID) (OrdersQuote, error) {
	row := q.db.QueryRow(ctx, getQuote, quoteUuid)
	var i OrdersQuote
	err := row.Scan(
		&i.QuoteUuid,
		&i.CustomerUuid,
		&i.RestaurantUuid,
		&i.DeliveryAddress,
		&i.CreatedAt,
		&i.ItemsSubtotalGross,
		&i.ServiceFeeGross,
		&i.DeliveryFeeGross,
		&i.TotalAmountGross,
		&i.TotalTax,
		&i.Currency,
	)
	return i, err
}

const getQuoteItems = `-- name: GetQuoteItems :many
SELECT quote_item_uuid, quote_uuid, menu_item_uuid, gross_price, quantity
FROM orders.quote_items
WHERE quote_uuid = $1
`

func (q *Queries) GetQuoteItems(ctx context.Context, quoteUuid app.QuoteUUID) ([]OrdersQuoteItem, error) {
	rows, err := q.db.Query(ctx, getQuoteItems, quoteUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrdersQuoteItem{}
	for rows.Next() {
		var i OrdersQuoteItem
		if err := rows.Scan(
			&i.QuoteItemUuid,
			&i.QuoteUuid,
			&i.MenuItemUuid,
			&i.GrossPrice,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
