// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: read_models.sql

package dbmodels

import (
	"context"

	"eats/backend/common/shared"
	"eats/backend/orders/app"
	"github.com/shopspring/decimal"
)

const listMenuItems = `-- name: ListMenuItems :many
SELECT
    mi.restaurant_menu_item_uuid AS menu_item_uuid,
    mi.name AS menu_item_name,
    mi.gross_price,
    r.currency,
    r.restaurant_uuid,
    r.name AS restaurant_name,
    CASE WHEN $1::text IS NOT NULL
         THEN ts_rank(
             to_tsvector('english', mi.name),
             plainto_tsquery('english', $1::text)
         )
         ELSE NULL
    END AS relevance
FROM orders.restaurant_menu_items mi
JOIN orders.restaurants r ON mi.restaurant_uuid = r.restaurant_uuid
WHERE mi.is_archived = false
  AND ($1::text IS NULL
       OR to_tsvector('english', mi.name) @@ plainto_tsquery('english', $1::text))
  AND ($2::text IS NULL
       OR LOWER(r.name) LIKE LOWER('%' || $2::text || '%'))
ORDER BY
    CASE WHEN $3::text = 'relevance'
         THEN ts_rank(
             to_tsvector('english', mi.name),
             plainto_tsquery('english', $1::text)
         )
    END DESC,
    CASE WHEN ($3::text IS NULL OR $3::text = 'default')
         THEN r.name END ASC,
    CASE WHEN ($3::text IS NULL OR $3::text = 'default')
         THEN mi.ordering END ASC,
    CASE WHEN $3::text = 'price_asc' THEN mi.gross_price END ASC,
    CASE WHEN $3::text = 'price_desc' THEN mi.gross_price END DESC,
    CASE WHEN $3::text = 'name_asc' THEN mi.name END ASC,
    CASE WHEN $3::text = 'name_desc' THEN mi.name END DESC
`

type ListMenuItemsParams struct {
	SearchTerm           *string
	RestaurantNameFilter *string
	OrderBy              *string
}

type ListMenuItemsRow struct {
	MenuItemUuid   app.RestaurantMenuItemUUID
	MenuItemName   string
	GrossPrice     decimal.Decimal
	Currency       shared.Currency
	RestaurantUuid app.RestaurantUUID
	RestaurantName string
	Relevance      interface{}
}

// Lists menu items with optional restaurant name filter, optional full-text search, and dynamic ordering.
// Uses CASE WHEN to support multiple ordering options in a single query.
func (q *Queries) ListMenuItems(ctx context.Context, arg ListMenuItemsParams) ([]ListMenuItemsRow, error) {
	rows, err := q.db.Query(ctx, listMenuItems, arg.SearchTerm, arg.RestaurantNameFilter, arg.OrderBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMenuItemsRow{}
	for rows.Next() {
		var i ListMenuItemsRow
		if err := rows.Scan(
			&i.MenuItemUuid,
			&i.MenuItemName,
			&i.GrossPrice,
			&i.Currency,
			&i.RestaurantUuid,
			&i.RestaurantName,
			&i.Relevance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
