// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package dbmodels

import (
	"context"
)

// iteratorForAddQuoteItems implements pgx.CopyFromSource.
type iteratorForAddQuoteItems struct {
	rows                 []AddQuoteItemsParams
	skippedFirstNextCall bool
}

func (r *iteratorForAddQuoteItems) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAddQuoteItems) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].QuoteItemUuid,
		r.rows[0].QuoteUuid,
		r.rows[0].MenuItemUuid,
		r.rows[0].GrossPrice,
		r.rows[0].Quantity,
	}, nil
}

func (r iteratorForAddQuoteItems) Err() error {
	return nil
}

func (q *Queries) AddQuoteItems(ctx context.Context, arg []AddQuoteItemsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"orders", "quote_items"}, []string{"quote_item_uuid", "quote_uuid", "menu_item_uuid", "gross_price", "quantity"}, &iteratorForAddQuoteItems{rows: arg})
}
