// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbmodels

import (
	"eats/backend/common/shared"
	"eats/backend/orders/app"
)

type OrdersCustomer struct {
	CustomerUuid app.CustomerUUID
	Name         string
	Email        string
	Address      shared.Address
	PhoneNumber  string
}
