// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbmodels

import (
	"eats/backend/common"
	"eats/backend/common/shared"
)

type OrdersCustomer struct {
	CustomerUuid common.UUID
	Name         string
	Email        string
	Address      shared.Address
	PhoneNumber  string
}
