// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: restaurants.sql

package dbmodels

import (
	"context"

	"eats/backend/common"
	"eats/backend/common/shared"
	"eats/backend/orders/app"
	"github.com/shopspring/decimal"
)

const archiveMenuItems = `-- name: ArchiveMenuItems :exec
UPDATE
	orders.restaurant_menu_items
SET
	is_archived = TRUE
WHERE
	restaurant_menu_item_uuid = ANY ($1::UUID[])
`

func (q *Queries) ArchiveMenuItems(ctx context.Context, dollar_1 []common.UUID) error {
	_, err := q.db.Exec(ctx, archiveMenuItems, dollar_1)
	return err
}

const getMenuItemsByUUIDs = `-- name: GetMenuItemsByUUIDs :many
SELECT
	restaurant_menu_items.restaurant_menu_item_uuid, restaurant_menu_items.restaurant_uuid, restaurant_menu_items.name, restaurant_menu_items.gross_price, restaurant_menu_items.ordering, restaurant_menu_items.is_archived
FROM
	orders.restaurant_menu_items AS restaurant_menu_items
WHERE
	restaurant_uuid = $1 AND
	restaurant_menu_item_uuid = ANY ($2::UUID[])
`

type GetMenuItemsByUUIDsParams struct {
	RestaurantUuid app.RestaurantUUID
	Column2        []common.UUID
}

func (q *Queries) GetMenuItemsByUUIDs(ctx context.Context, arg GetMenuItemsByUUIDsParams) ([]OrdersRestaurantMenuItem, error) {
	rows, err := q.db.Query(ctx, getMenuItemsByUUIDs, arg.RestaurantUuid, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrdersRestaurantMenuItem{}
	for rows.Next() {
		var i OrdersRestaurantMenuItem
		if err := rows.Scan(
			&i.RestaurantMenuItemUuid,
			&i.RestaurantUuid,
			&i.Name,
			&i.GrossPrice,
			&i.Ordering,
			&i.IsArchived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRestaurant = `-- name: GetRestaurant :one
SELECT
	restaurant_uuid, name, description, address, currency
FROM
	orders.restaurants
WHERE
	restaurant_uuid = $1
`

func (q *Queries) GetRestaurant(ctx context.Context, restaurantUuid app.RestaurantUUID) (OrdersRestaurant, error) {
	row := q.db.QueryRow(ctx, getRestaurant, restaurantUuid)
	var i OrdersRestaurant
	err := row.Scan(
		&i.RestaurantUuid,
		&i.Name,
		&i.Description,
		&i.Address,
		&i.Currency,
	)
	return i, err
}

const getRestaurantMenu = `-- name: GetRestaurantMenu :many
SELECT
	restaurant_menu_items.restaurant_menu_item_uuid, restaurant_menu_items.restaurant_uuid, restaurant_menu_items.name, restaurant_menu_items.gross_price, restaurant_menu_items.ordering, restaurant_menu_items.is_archived
FROM
	orders.restaurant_menu_items AS restaurant_menu_items
WHERE
	restaurant_uuid = $1 AND
	is_archived = FALSE
ORDER BY
	ordering ASC
`

type GetRestaurantMenuRow struct {
	OrdersRestaurantMenuItem OrdersRestaurantMenuItem
}

func (q *Queries) GetRestaurantMenu(ctx context.Context, restaurantUuid app.RestaurantUUID) ([]GetRestaurantMenuRow, error) {
	rows, err := q.db.Query(ctx, getRestaurantMenu, restaurantUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRestaurantMenuRow{}
	for rows.Next() {
		var i GetRestaurantMenuRow
		if err := rows.Scan(
			&i.OrdersRestaurantMenuItem.RestaurantMenuItemUuid,
			&i.OrdersRestaurantMenuItem.RestaurantUuid,
			&i.OrdersRestaurantMenuItem.Name,
			&i.OrdersRestaurantMenuItem.GrossPrice,
			&i.OrdersRestaurantMenuItem.Ordering,
			&i.OrdersRestaurantMenuItem.IsArchived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRestaurant = `-- name: UpsertRestaurant :one
INSERT INTO orders.restaurants (restaurant_uuid, name, description, address, currency)
VALUES
	($1, $2, $3, $4, $5)
ON CONFLICT (restaurant_uuid) DO UPDATE SET
	name = EXCLUDED.name,
	description = EXCLUDED.description,
	address = EXCLUDED.address
RETURNING restaurant_uuid, name, description, address, currency
`

type UpsertRestaurantParams struct {
	RestaurantUuid app.RestaurantUUID
	Name           string
	Description    string
	Address        shared.Address
	Currency       shared.Currency
}

func (q *Queries) UpsertRestaurant(ctx context.Context, arg UpsertRestaurantParams) (OrdersRestaurant, error) {
	row := q.db.QueryRow(ctx, upsertRestaurant,
		arg.RestaurantUuid,
		arg.Name,
		arg.Description,
		arg.Address,
		arg.Currency,
	)
	var i OrdersRestaurant
	err := row.Scan(
		&i.RestaurantUuid,
		&i.Name,
		&i.Description,
		&i.Address,
		&i.Currency,
	)
	return i, err
}

const upsertRestaurantMenuItem = `-- name: UpsertRestaurantMenuItem :exec
INSERT INTO orders.restaurant_menu_items (
	restaurant_menu_item_uuid,
	restaurant_uuid,
	name,
	gross_price,
	ordering,
	is_archived
)
VALUES
	($1, $2, $3, $4, $5, $6)
ON CONFLICT (restaurant_menu_item_uuid) DO UPDATE SET
	restaurant_uuid = EXCLUDED.restaurant_uuid,
	name = EXCLUDED.name,
	gross_price = EXCLUDED.gross_price,
	ordering = EXCLUDED.ordering,
	is_archived = EXCLUDED.is_archived
`

type UpsertRestaurantMenuItemParams struct {
	RestaurantMenuItemUuid app.RestaurantMenuItemUUID
	RestaurantUuid         app.RestaurantUUID
	Name                   string
	GrossPrice             decimal.Decimal
	Ordering               float64
	IsArchived             bool
}

func (q *Queries) UpsertRestaurantMenuItem(ctx context.Context, arg UpsertRestaurantMenuItemParams) error {
	_, err := q.db.Exec(ctx, upsertRestaurantMenuItem,
		arg.RestaurantMenuItemUuid,
		arg.RestaurantUuid,
		arg.Name,
		arg.GrossPrice,
		arg.Ordering,
		arg.IsArchived,
	)
	return err
}
