// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_test.sql

package dbtests

import (
	"context"
)

const getDocumentsBySeriesPrefix = `-- name: GetDocumentsBySeriesPrefix :many
SELECT document_number FROM billing.documents WHERE series_prefix = $1 ORDER BY document_number
`

func (q *Queries) GetDocumentsBySeriesPrefix(ctx context.Context, seriesPrefix string) ([]string, error) {
	rows, err := q.db.Query(ctx, getDocumentsBySeriesPrefix, seriesPrefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var document_number string
		if err := rows.Scan(&document_number); err != nil {
			return nil, err
		}
		items = append(items, document_number)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveDocumentSeries = `-- name: SaveDocumentSeries :exec
INSERT INTO billing.document_series (prefix)
VALUES ($1)
ON CONFLICT DO NOTHING
`

func (q *Queries) SaveDocumentSeries(ctx context.Context, prefix string) error {
	_, err := q.db.Exec(ctx, saveDocumentSeries, prefix)
	return err
}
