// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbtests

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BillingDocument struct {
	DocumentUuid      pgtype.UUID
	ExternalReference pgtype.Text
	DocumentNumber    string
	SeriesPrefix      string
}

type BillingDocumentSeries struct {
	Prefix     string
	LastNumber int32
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}
