// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: couriers.sql

package dbmodels

import (
	"context"

	"eats/backend/orders/app"
)

const getCourierCity = `-- name: GetCourierCity :one
SELECT
	city
FROM
	orders.couriers
WHERE
	courier_uuid = $1
`

func (q *Queries) GetCourierCity(ctx context.Context, courierUuid app.CourierUUID) (string, error) {
	row := q.db.QueryRow(ctx, getCourierCity, courierUuid)
	var city string
	err := row.Scan(&city)
	return city, err
}

const insertCourier = `-- name: InsertCourier :exec
INSERT INTO orders.couriers (
	courier_uuid,
	name,
	phone_number,
	city
)
VALUES
	($1, $2, $3, $4)
`

type InsertCourierParams struct {
	CourierUuid app.CourierUUID
	Name        string
	PhoneNumber string
	City        string
}

func (q *Queries) InsertCourier(ctx context.Context, arg InsertCourierParams) error {
	_, err := q.db.Exec(ctx, insertCourier,
		arg.CourierUuid,
		arg.Name,
		arg.PhoneNumber,
		arg.City,
	)
	return err
}
