// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package dbmodels

import (
	"context"
	"time"

	"eats/backend/common"
	"eats/backend/common/shared"
	"eats/backend/orders/app"
	"github.com/shopspring/decimal"
)

const addOrder = `-- name: AddOrder :exec
INSERT INTO orders.orders (
	order_uuid,
	quote_uuid,
	customer_uuid,
	restaurant_uuid,
	delivery_address,
	items_subtotal_gross,
	service_fee_gross,
	delivery_fee_gross,
	total_amount_gross,
	total_tax,
	ordered_at,
	currency
)
VALUES
	($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (order_uuid) DO NOTHING
`

type AddOrderParams struct {
	OrderUuid          app.OrderUUID
	QuoteUuid          app.QuoteUUID
	CustomerUuid       app.CustomerUUID
	RestaurantUuid     app.RestaurantUUID
	DeliveryAddress    shared.Address
	ItemsSubtotalGross decimal.Decimal
	ServiceFeeGross    decimal.Decimal
	DeliveryFeeGross   decimal.Decimal
	TotalAmountGross   decimal.Decimal
	TotalTax           decimal.Decimal
	OrderedAt          time.Time
	Currency           shared.Currency
}

func (q *Queries) AddOrder(ctx context.Context, arg AddOrderParams) error {
	_, err := q.db.Exec(ctx, addOrder,
		arg.OrderUuid,
		arg.QuoteUuid,
		arg.CustomerUuid,
		arg.RestaurantUuid,
		arg.DeliveryAddress,
		arg.ItemsSubtotalGross,
		arg.ServiceFeeGross,
		arg.DeliveryFeeGross,
		arg.TotalAmountGross,
		arg.TotalTax,
		arg.OrderedAt,
		arg.Currency,
	)
	return err
}

const addQuote = `-- name: AddQuote :exec
INSERT INTO orders.quotes (
	quote_uuid,
	customer_uuid,
	restaurant_uuid,
	delivery_address,
	items_subtotal_gross,
	service_fee_gross,
	delivery_fee_gross,
	total_amount_gross,
	total_tax,
	created_at,
	currency
)
VALUES
	($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type AddQuoteParams struct {
	QuoteUuid          app.QuoteUUID
	CustomerUuid       app.CustomerUUID
	RestaurantUuid     app.RestaurantUUID
	DeliveryAddress    shared.Address
	ItemsSubtotalGross decimal.Decimal
	ServiceFeeGross    decimal.Decimal
	DeliveryFeeGross   decimal.Decimal
	TotalAmountGross   decimal.Decimal
	TotalTax           decimal.Decimal
	CreatedAt          time.Time
	Currency           shared.Currency
}

// Quotes are immutable - no update query exists. If needed, create a new quote.
func (q *Queries) AddQuote(ctx context.Context, arg AddQuoteParams) error {
	_, err := q.db.Exec(ctx, addQuote,
		arg.QuoteUuid,
		arg.CustomerUuid,
		arg.RestaurantUuid,
		arg.DeliveryAddress,
		arg.ItemsSubtotalGross,
		arg.ServiceFeeGross,
		arg.DeliveryFeeGross,
		arg.TotalAmountGross,
		arg.TotalTax,
		arg.CreatedAt,
		arg.Currency,
	)
	return err
}

type AddQuoteItemsParams struct {
	QuoteItemUuid common.UUID
	QuoteUuid     app.QuoteUUID
	MenuItemUuid  app.RestaurantMenuItemUUID
	GrossPrice    decimal.Decimal
	Quantity      int32
}

const getAvailableOrdersForCourier = `-- name: GetAvailableOrdersForCourier :many
SELECT
	orders.order_uuid,
	orders.customer_uuid,
	orders.courier_uuid,
	orders.ordered_at,
	orders.restaurant_confirmed_at,
	orders.courier_accepted_at,
	orders.restaurant_prepared_at,
	orders.picked_up_at,
	orders.delivered_at,
	orders.items_subtotal_gross,
	orders.delivery_address,
	orders.restaurant_uuid,
	orders.currency,
	restaurants.name AS restaurant_name
FROM
	orders.orders AS orders
	INNER JOIN orders.restaurants restaurants USING (restaurant_uuid)
WHERE
	orders.restaurant_confirmed_at IS NOT NULL AND
	orders.courier_uuid IS NULL AND
	orders.delivered_at IS NULL AND
	(orders.delivery_address ->> 'city') = (
		SELECT
			city
		FROM
			orders.couriers
		WHERE
			couriers.courier_uuid = $1
	)
`

type GetAvailableOrdersForCourierRow struct {
	OrderUuid             app.OrderUUID
	CustomerUuid          app.CustomerUUID
	CourierUuid           *app.CourierUUID
	OrderedAt             time.Time
	RestaurantConfirmedAt *time.Time
	CourierAcceptedAt     *time.Time
	RestaurantPreparedAt  *time.Time
	PickedUpAt            *time.Time
	DeliveredAt           *time.Time
	ItemsSubtotalGross    decimal.Decimal
	DeliveryAddress       shared.Address
	RestaurantUuid        app.RestaurantUUID
	Currency              shared.Currency
	RestaurantName        string
}

func (q *Queries) GetAvailableOrdersForCourier(ctx context.Context, courierUuid app.CourierUUID) ([]GetAvailableOrdersForCourierRow, error) {
	rows, err := q.db.Query(ctx, getAvailableOrdersForCourier, courierUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAvailableOrdersForCourierRow{}
	for rows.Next() {
		var i GetAvailableOrdersForCourierRow
		if err := rows.Scan(
			&i.OrderUuid,
			&i.CustomerUuid,
			&i.CourierUuid,
			&i.OrderedAt,
			&i.RestaurantConfirmedAt,
			&i.CourierAcceptedAt,
			&i.RestaurantPreparedAt,
			&i.PickedUpAt,
			&i.DeliveredAt,
			&i.ItemsSubtotalGross,
			&i.DeliveryAddress,
			&i.RestaurantUuid,
			&i.Currency,
			&i.RestaurantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCourierOrders = `-- name: GetCourierOrders :many
SELECT
	orders.order_uuid,
	orders.customer_uuid,
	orders.courier_uuid,
	orders.ordered_at,
	orders.restaurant_confirmed_at,
	orders.courier_accepted_at,
	orders.restaurant_prepared_at,
	orders.picked_up_at,
	orders.delivered_at,
	orders.items_subtotal_gross,
	orders.delivery_address,
	orders.restaurant_uuid,
	orders.currency,
	restaurants.name AS restaurant_name
FROM
	orders.orders AS orders
	INNER JOIN orders.restaurants restaurants USING (restaurant_uuid)
WHERE
	orders.courier_uuid = $1
ORDER BY
	orders.ordered_at DESC
`

type GetCourierOrdersRow struct {
	OrderUuid             app.OrderUUID
	CustomerUuid          app.CustomerUUID
	CourierUuid           *app.CourierUUID
	OrderedAt             time.Time
	RestaurantConfirmedAt *time.Time
	CourierAcceptedAt     *time.Time
	RestaurantPreparedAt  *time.Time
	PickedUpAt            *time.Time
	DeliveredAt           *time.Time
	ItemsSubtotalGross    decimal.Decimal
	DeliveryAddress       shared.Address
	RestaurantUuid        app.RestaurantUUID
	Currency              shared.Currency
	RestaurantName        string
}

func (q *Queries) GetCourierOrders(ctx context.Context, courierUuid *app.CourierUUID) ([]GetCourierOrdersRow, error) {
	rows, err := q.db.Query(ctx, getCourierOrders, courierUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCourierOrdersRow{}
	for rows.Next() {
		var i GetCourierOrdersRow
		if err := rows.Scan(
			&i.OrderUuid,
			&i.CustomerUuid,
			&i.CourierUuid,
			&i.OrderedAt,
			&i.RestaurantConfirmedAt,
			&i.CourierAcceptedAt,
			&i.RestaurantPreparedAt,
			&i.PickedUpAt,
			&i.DeliveredAt,
			&i.ItemsSubtotalGross,
			&i.DeliveryAddress,
			&i.RestaurantUuid,
			&i.Currency,
			&i.RestaurantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomerOrders = `-- name: GetCustomerOrders :many
SELECT
	orders.order_uuid,
	orders.restaurant_uuid,
	orders.courier_uuid,
	orders.delivery_address,
	orders.ordered_at,
	orders.restaurant_confirmed_at,
	orders.courier_accepted_at,
	orders.restaurant_prepared_at,
	orders.picked_up_at,
	orders.delivered_at,
	orders.items_subtotal_gross,
	orders.service_fee_gross,
	orders.delivery_fee_gross,
	orders.total_amount_gross,
	orders.total_tax,
	orders.currency,
	restaurants.name AS restaurant_name
FROM
	orders.orders AS orders
	INNER JOIN orders.restaurants restaurants USING (restaurant_uuid)
WHERE
	orders.customer_uuid = $1
ORDER BY
	orders.ordered_at DESC
`

type GetCustomerOrdersRow struct {
	OrderUuid             app.OrderUUID
	RestaurantUuid        app.RestaurantUUID
	CourierUuid           *app.CourierUUID
	DeliveryAddress       shared.Address
	OrderedAt             time.Time
	RestaurantConfirmedAt *time.Time
	CourierAcceptedAt     *time.Time
	RestaurantPreparedAt  *time.Time
	PickedUpAt            *time.Time
	DeliveredAt           *time.Time
	ItemsSubtotalGross    decimal.Decimal
	ServiceFeeGross       decimal.Decimal
	DeliveryFeeGross      decimal.Decimal
	TotalAmountGross      decimal.Decimal
	TotalTax              decimal.Decimal
	Currency              shared.Currency
	RestaurantName        string
}

func (q *Queries) GetCustomerOrders(ctx context.Context, customerUuid app.CustomerUUID) ([]GetCustomerOrdersRow, error) {
	rows, err := q.db.Query(ctx, getCustomerOrders, customerUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCustomerOrdersRow{}
	for rows.Next() {
		var i GetCustomerOrdersRow
		if err := rows.Scan(
			&i.OrderUuid,
			&i.RestaurantUuid,
			&i.CourierUuid,
			&i.DeliveryAddress,
			&i.OrderedAt,
			&i.RestaurantConfirmedAt,
			&i.CourierAcceptedAt,
			&i.RestaurantPreparedAt,
			&i.PickedUpAt,
			&i.DeliveredAt,
			&i.ItemsSubtotalGross,
			&i.ServiceFeeGross,
			&i.DeliveryFeeGross,
			&i.TotalAmountGross,
			&i.TotalTax,
			&i.Currency,
			&i.RestaurantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMenuItemsForQuote = `-- name: GetMenuItemsForQuote :many
SELECT
	restaurant_menu_items.restaurant_menu_item_uuid, restaurant_menu_items.restaurant_uuid, restaurant_menu_items.name, restaurant_menu_items.gross_price, restaurant_menu_items.ordering, restaurant_menu_items.is_archived
FROM
	orders.restaurant_menu_items AS restaurant_menu_items
	INNER JOIN orders.quote_items AS quote_items
	           ON restaurant_menu_items.restaurant_menu_item_uuid = quote_items.menu_item_uuid
WHERE
	quote_items.quote_uuid = $1
`

// Joining via quote_items avoids a separate query - one roundtrip instead of two.
func (q *Queries) GetMenuItemsForQuote(ctx context.Context, quoteUuid app.QuoteUUID) ([]OrdersRestaurantMenuItem, error) {
	rows, err := q.db.Query(ctx, getMenuItemsForQuote, quoteUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrdersRestaurantMenuItem{}
	for rows.Next() {
		var i OrdersRestaurantMenuItem
		if err := rows.Scan(
			&i.RestaurantMenuItemUuid,
			&i.RestaurantUuid,
			&i.Name,
			&i.GrossPrice,
			&i.Ordering,
			&i.IsArchived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrder = `-- name: GetOrder :one
SELECT
	order_uuid, quote_uuid, customer_uuid, restaurant_uuid, courier_uuid, delivery_address, ordered_at, restaurant_confirmed_at, courier_accepted_at, restaurant_prepared_at, picked_up_at, delivered_at, items_subtotal_gross, service_fee_gross, delivery_fee_gross, total_amount_gross, total_tax, currency
FROM
	orders.orders AS orders
WHERE
	order_uuid = $1
LIMIT 1
`

func (q *Queries) GetOrder(ctx context.Context, orderUuid app.OrderUUID) (OrdersOrder, error) {
	row := q.db.QueryRow(ctx, getOrder, orderUuid)
	var i OrdersOrder
	err := row.Scan(
		&i.OrderUuid,
		&i.QuoteUuid,
		&i.CustomerUuid,
		&i.RestaurantUuid,
		&i.CourierUuid,
		&i.DeliveryAddress,
		&i.OrderedAt,
		&i.RestaurantConfirmedAt,
		&i.CourierAcceptedAt,
		&i.RestaurantPreparedAt,
		&i.PickedUpAt,
		&i.DeliveredAt,
		&i.ItemsSubtotalGross,
		&i.ServiceFeeGross,
		&i.DeliveryFeeGross,
		&i.TotalAmountGross,
		&i.TotalTax,
		&i.Currency,
	)
	return i, err
}

const getQuote = `-- name: GetQuote :one
SELECT
	quote_uuid, customer_uuid, restaurant_uuid, delivery_address, created_at, items_subtotal_gross, service_fee_gross, delivery_fee_gross, total_amount_gross, total_tax, currency
FROM
	orders.quotes AS quotes
WHERE
	quote_uuid = $1
LIMIT 1
`

func (q *Queries) GetQuote(ctx context.Context, quoteUuid app.QuoteUUID) (OrdersQuote, error) {
	row := q.db.QueryRow(ctx, getQuote, quoteUuid)
	var i OrdersQuote
	err := row.Scan(
		&i.QuoteUuid,
		&i.CustomerUuid,
		&i.RestaurantUuid,
		&i.DeliveryAddress,
		&i.CreatedAt,
		&i.ItemsSubtotalGross,
		&i.ServiceFeeGross,
		&i.DeliveryFeeGross,
		&i.TotalAmountGross,
		&i.TotalTax,
		&i.Currency,
	)
	return i, err
}

const getQuoteItems = `-- name: GetQuoteItems :many
SELECT quote_item_uuid, quote_uuid, menu_item_uuid, gross_price, quantity
FROM orders.quote_items
WHERE quote_uuid = $1
`

func (q *Queries) GetQuoteItems(ctx context.Context, quoteUuid app.QuoteUUID) ([]OrdersQuoteItem, error) {
	rows, err := q.db.Query(ctx, getQuoteItems, quoteUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrdersQuoteItem{}
	for rows.Next() {
		var i OrdersQuoteItem
		if err := rows.Scan(
			&i.QuoteItemUuid,
			&i.QuoteUuid,
			&i.MenuItemUuid,
			&i.GrossPrice,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRestaurantOrders = `-- name: GetRestaurantOrders :many
SELECT
	orders.order_uuid,
	orders.customer_uuid,
	orders.courier_uuid,
	orders.ordered_at,
	orders.restaurant_confirmed_at,
	orders.courier_accepted_at,
	orders.restaurant_prepared_at,
	orders.picked_up_at,
	orders.delivered_at,
	orders.items_subtotal_gross,
	orders.currency
FROM
	orders.orders AS orders
WHERE
	orders.restaurant_uuid = $1
ORDER BY
	orders.ordered_at DESC
`

type GetRestaurantOrdersRow struct {
	OrderUuid             app.OrderUUID
	CustomerUuid          app.CustomerUUID
	CourierUuid           *app.CourierUUID
	OrderedAt             time.Time
	RestaurantConfirmedAt *time.Time
	CourierAcceptedAt     *time.Time
	RestaurantPreparedAt  *time.Time
	PickedUpAt            *time.Time
	DeliveredAt           *time.Time
	ItemsSubtotalGross    decimal.Decimal
	Currency              shared.Currency
}

func (q *Queries) GetRestaurantOrders(ctx context.Context, restaurantUuid app.RestaurantUUID) ([]GetRestaurantOrdersRow, error) {
	rows, err := q.db.Query(ctx, getRestaurantOrders, restaurantUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRestaurantOrdersRow{}
	for rows.Next() {
		var i GetRestaurantOrdersRow
		if err := rows.Scan(
			&i.OrderUuid,
			&i.CustomerUuid,
			&i.CourierUuid,
			&i.OrderedAt,
			&i.RestaurantConfirmedAt,
			&i.CourierAcceptedAt,
			&i.RestaurantPreparedAt,
			&i.PickedUpAt,
			&i.DeliveredAt,
			&i.ItemsSubtotalGross,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrder = `-- name: UpdateOrder :exec
UPDATE
	orders.orders
SET
	courier_uuid = COALESCE($2, courier_uuid),
	ordered_at = COALESCE($3, ordered_at),
	restaurant_confirmed_at = COALESCE($4, restaurant_confirmed_at),
	courier_accepted_at = COALESCE($5, courier_accepted_at),
	restaurant_prepared_at = COALESCE($6, restaurant_prepared_at),
	picked_up_at = COALESCE($7, picked_up_at),
	delivered_at = COALESCE($8, delivered_at)
WHERE
	order_uuid = $1
`

type UpdateOrderParams struct {
	OrderUuid             app.OrderUUID
	CourierUuid           *app.CourierUUID
	OrderedAt             *time.Time
	RestaurantConfirmedAt *time.Time
	CourierAcceptedAt     *time.Time
	RestaurantPreparedAt  *time.Time
	PickedUpAt            *time.Time
	DeliveredAt           *time.Time
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) error {
	_, err := q.db.Exec(ctx, updateOrder,
		arg.OrderUuid,
		arg.CourierUuid,
		arg.OrderedAt,
		arg.RestaurantConfirmedAt,
		arg.CourierAcceptedAt,
		arg.RestaurantPreparedAt,
		arg.PickedUpAt,
		arg.DeliveredAt,
	)
	return err
}
