// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: billing_cycles.sql

package dbmodels

import (
	"context"
	"time"

	"eats/backend/common/shared"
	"eats/backend/settlements/app/models"
	"eats/backend/settlements/domain"
	"github.com/shopspring/decimal"
)

const addOrderToBillingCycle = `-- name: AddOrderToBillingCycle :exec
INSERT INTO settlements.billing_cycle_orders (billing_cycle_uuid, order_uuid)
VALUES (
           $1, $2
)
ON CONFLICT (billing_cycle_uuid, order_uuid) DO NOTHING
`

type AddOrderToBillingCycleParams struct {
	BillingCycleUuid domain.BillingCycleUUID
	OrderUuid        models.OrderUUID
}

func (q *Queries) AddOrderToBillingCycle(ctx context.Context, arg AddOrderToBillingCycleParams) error {
	_, err := q.db.Exec(ctx, addOrderToBillingCycle, arg.BillingCycleUuid, arg.OrderUuid)
	return err
}

const billingCyclesByPartnerUUID = `-- name: BillingCyclesByPartnerUUID :many
SELECT billing_cycle_uuid, partner_uuid, partner_type, billing_cycle_number, closed, settled, start_date, end_date
FROM settlements.billing_cycles
WHERE partner_uuid = $1
ORDER BY billing_cycle_number DESC
`

func (q *Queries) BillingCyclesByPartnerUUID(ctx context.Context, partnerUuid domain.LegalEntityUUID) ([]SettlementsBillingCycle, error) {
	rows, err := q.db.Query(ctx, billingCyclesByPartnerUUID, partnerUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SettlementsBillingCycle{}
	for rows.Next() {
		var i SettlementsBillingCycle
		if err := rows.Scan(
			&i.BillingCycleUuid,
			&i.PartnerUuid,
			&i.PartnerType,
			&i.BillingCycleNumber,
			&i.Closed,
			&i.Settled,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const commissionInvoiceByBillingCycleUUID = `-- name: CommissionInvoiceByBillingCycleUUID :one
SELECT
    bc.partner_uuid AS buyer_uuid,
    COUNT(o.order_uuid) AS quantity,
    SUM(o.commission_net_amount)::DECIMAL AS net_amount
FROM settlements.orders o
JOIN settlements.billing_cycle_orders bco ON o.order_uuid = bco.order_uuid
JOIN settlements.billing_cycles bc USING (billing_cycle_uuid)
WHERE bc.billing_cycle_uuid = $1
    AND bc.partner_type = 'restaurant'
GROUP BY bc.partner_uuid
`

type CommissionInvoiceByBillingCycleUUIDRow struct {
	BuyerUuid domain.LegalEntityUUID
	Quantity  int64
	NetAmount decimal.Decimal
}

func (q *Queries) CommissionInvoiceByBillingCycleUUID(ctx context.Context, billingCycleUuid domain.BillingCycleUUID) (CommissionInvoiceByBillingCycleUUIDRow, error) {
	row := q.db.QueryRow(ctx, commissionInvoiceByBillingCycleUUID, billingCycleUuid)
	var i CommissionInvoiceByBillingCycleUUIDRow
	err := row.Scan(&i.BuyerUuid, &i.Quantity, &i.NetAmount)
	return i, err
}

const currentBillingCycle = `-- name: CurrentBillingCycle :one
SELECT billing_cycle_uuid, partner_uuid, partner_type, billing_cycle_number, closed, settled, start_date, end_date FROM settlements.billing_cycles
WHERE partner_uuid = $1 AND closed = false
LIMIT 1
`

func (q *Queries) CurrentBillingCycle(ctx context.Context, partnerUuid domain.LegalEntityUUID) (SettlementsBillingCycle, error) {
	row := q.db.QueryRow(ctx, currentBillingCycle, partnerUuid)
	var i SettlementsBillingCycle
	err := row.Scan(
		&i.BillingCycleUuid,
		&i.PartnerUuid,
		&i.PartnerType,
		&i.BillingCycleNumber,
		&i.Closed,
		&i.Settled,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const deliveryInvoicesByBillingCycleUUID = `-- name: DeliveryInvoicesByBillingCycleUUID :many
SELECT
    bc.partner_uuid AS seller_uuid,
    o.restaurant_uuid AS buyer_uuid,
    COUNT(o.order_uuid) AS quantity,
    SUM(ob.net_amount)::DECIMAL AS net_amount
FROM settlements.orders o
JOIN settlements.order_breakdowns ob ON o.order_uuid = ob.order_uuid AND ob.breakdown_type = 'delivery'
JOIN settlements.billing_cycle_orders bco ON o.order_uuid = bco.order_uuid
JOIN settlements.billing_cycles bc USING (billing_cycle_uuid)
WHERE bc.billing_cycle_uuid = $1
    AND bc.partner_type = 'courier'
GROUP BY (bc.partner_uuid, o.restaurant_uuid)
ORDER BY (bc.partner_uuid, o.restaurant_uuid)
`

type DeliveryInvoicesByBillingCycleUUIDRow struct {
	SellerUuid domain.LegalEntityUUID
	BuyerUuid  domain.LegalEntityUUID
	Quantity   int64
	NetAmount  decimal.Decimal
}

func (q *Queries) DeliveryInvoicesByBillingCycleUUID(ctx context.Context, billingCycleUuid domain.BillingCycleUUID) ([]DeliveryInvoicesByBillingCycleUUIDRow, error) {
	rows, err := q.db.Query(ctx, deliveryInvoicesByBillingCycleUUID, billingCycleUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeliveryInvoicesByBillingCycleUUIDRow{}
	for rows.Next() {
		var i DeliveryInvoicesByBillingCycleUUIDRow
		if err := rows.Scan(
			&i.SellerUuid,
			&i.BuyerUuid,
			&i.Quantity,
			&i.NetAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBillingCycleByUUID = `-- name: GetBillingCycleByUUID :one
SELECT billing_cycle_uuid, partner_uuid, partner_type, billing_cycle_number, closed, settled, start_date, end_date FROM settlements.billing_cycles
WHERE billing_cycle_uuid = $1
`

func (q *Queries) GetBillingCycleByUUID(ctx context.Context, billingCycleUuid domain.BillingCycleUUID) (SettlementsBillingCycle, error) {
	row := q.db.QueryRow(ctx, getBillingCycleByUUID, billingCycleUuid)
	var i SettlementsBillingCycle
	err := row.Scan(
		&i.BillingCycleUuid,
		&i.PartnerUuid,
		&i.PartnerType,
		&i.BillingCycleNumber,
		&i.Closed,
		&i.Settled,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const orderBreakdownsByBillingCycleUUID = `-- name: OrderBreakdownsByBillingCycleUUID :many
SELECT ob.order_uuid, ob.breakdown_type, ob.net_amount, ob.tax_amount, ob.gross_amount
FROM settlements.order_breakdowns ob
INNER JOIN settlements.billing_cycle_orders bco USING (order_uuid)
WHERE bco.billing_cycle_uuid = $1
`

func (q *Queries) OrderBreakdownsByBillingCycleUUID(ctx context.Context, billingCycleUuid domain.BillingCycleUUID) ([]SettlementsOrderBreakdown, error) {
	rows, err := q.db.Query(ctx, orderBreakdownsByBillingCycleUUID, billingCycleUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SettlementsOrderBreakdown{}
	for rows.Next() {
		var i SettlementsOrderBreakdown
		if err := rows.Scan(
			&i.OrderUuid,
			&i.BreakdownType,
			&i.NetAmount,
			&i.TaxAmount,
			&i.GrossAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orderInPartnerBillingCycleExists = `-- name: OrderInPartnerBillingCycleExists :one
SELECT EXISTS(
    SELECT 1 FROM settlements.billing_cycle_orders bco
    INNER JOIN settlements.billing_cycles bc ON bco.billing_cycle_uuid = bc.billing_cycle_uuid
    WHERE bco.order_uuid = $1
      AND bc.partner_uuid = $2
)
`

type OrderInPartnerBillingCycleExistsParams struct {
	OrderUuid   models.OrderUUID
	PartnerUuid domain.LegalEntityUUID
}

func (q *Queries) OrderInPartnerBillingCycleExists(ctx context.Context, arg OrderInPartnerBillingCycleExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, orderInPartnerBillingCycleExists, arg.OrderUuid, arg.PartnerUuid)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const ordersByBillingCycleUUID = `-- name: OrdersByBillingCycleUUID :many
SELECT orders.order_uuid, restaurant_uuid, courier_uuid, currency, commission_net_amount, ordered_at, billing_cycle_uuid, billing_cycle_orders.order_uuid FROM settlements.orders
INNER JOIN settlements.billing_cycle_orders USING (order_uuid)
WHERE billing_cycle_uuid = $1
`

type OrdersByBillingCycleUUIDRow struct {
	OrderUuid           models.OrderUUID
	RestaurantUuid      domain.LegalEntityUUID
	CourierUuid         domain.LegalEntityUUID
	Currency            shared.Currency
	CommissionNetAmount decimal.Decimal
	OrderedAt           time.Time
	BillingCycleUuid    domain.BillingCycleUUID
	OrderUuid_2         models.OrderUUID
}

func (q *Queries) OrdersByBillingCycleUUID(ctx context.Context, billingCycleUuid domain.BillingCycleUUID) ([]OrdersByBillingCycleUUIDRow, error) {
	rows, err := q.db.Query(ctx, ordersByBillingCycleUUID, billingCycleUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrdersByBillingCycleUUIDRow{}
	for rows.Next() {
		var i OrdersByBillingCycleUUIDRow
		if err := rows.Scan(
			&i.OrderUuid,
			&i.RestaurantUuid,
			&i.CourierUuid,
			&i.Currency,
			&i.CommissionNetAmount,
			&i.OrderedAt,
			&i.BillingCycleUuid,
			&i.OrderUuid_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveBillingCycle = `-- name: SaveBillingCycle :exec
INSERT INTO settlements.billing_cycles (billing_cycle_uuid, partner_uuid, partner_type, billing_cycle_number, closed, settled, start_date, end_date)
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8
       )
ON CONFLICT (billing_cycle_uuid) DO UPDATE SET
   -- Other fields are immutable
    closed = EXCLUDED.closed,
    settled = EXCLUDED.settled,
    end_date = EXCLUDED.end_date
`

type SaveBillingCycleParams struct {
	BillingCycleUuid   domain.BillingCycleUUID
	PartnerUuid        domain.LegalEntityUUID
	PartnerType        domain.PartnerType
	BillingCycleNumber int32
	Closed             bool
	Settled            bool
	StartDate          time.Time
	EndDate            *time.Time
}

func (q *Queries) SaveBillingCycle(ctx context.Context, arg SaveBillingCycleParams) error {
	_, err := q.db.Exec(ctx, saveBillingCycle,
		arg.BillingCycleUuid,
		arg.PartnerUuid,
		arg.PartnerType,
		arg.BillingCycleNumber,
		arg.Closed,
		arg.Settled,
		arg.StartDate,
		arg.EndDate,
	)
	return err
}

const unsettledClosedCycles = `-- name: UnsettledClosedCycles :many
SELECT billing_cycle_uuid, partner_uuid, partner_type, billing_cycle_number, closed, settled, start_date, end_date FROM settlements.billing_cycles
WHERE partner_uuid = $1 AND closed = true AND settled = false
ORDER BY billing_cycle_number ASC
`

func (q *Queries) UnsettledClosedCycles(ctx context.Context, partnerUuid domain.LegalEntityUUID) ([]SettlementsBillingCycle, error) {
	rows, err := q.db.Query(ctx, unsettledClosedCycles, partnerUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SettlementsBillingCycle{}
	for rows.Next() {
		var i SettlementsBillingCycle
		if err := rows.Scan(
			&i.BillingCycleUuid,
			&i.PartnerUuid,
			&i.PartnerType,
			&i.BillingCycleNumber,
			&i.Closed,
			&i.Settled,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
