// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbmodels

import (
	"database/sql/driver"
	"fmt"
	"time"

	"eats/backend/common/shared"
	"eats/backend/settlements/app/models"
	"eats/backend/settlements/domain"
	"github.com/shopspring/decimal"
)

type SettlementsBreakdownType string

const (
	SettlementsBreakdownTypeItems    SettlementsBreakdownType = "items"
	SettlementsBreakdownTypeDelivery SettlementsBreakdownType = "delivery"
	SettlementsBreakdownTypeTotal    SettlementsBreakdownType = "total"
)

func (e *SettlementsBreakdownType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SettlementsBreakdownType(s)
	case string:
		*e = SettlementsBreakdownType(s)
	default:
		return fmt.Errorf("unsupported scan type for SettlementsBreakdownType: %T", src)
	}
	return nil
}

type NullSettlementsBreakdownType struct {
	SettlementsBreakdownType SettlementsBreakdownType
	Valid                    bool // Valid is true if SettlementsBreakdownType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSettlementsBreakdownType) Scan(value interface{}) error {
	if value == nil {
		ns.SettlementsBreakdownType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SettlementsBreakdownType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSettlementsBreakdownType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SettlementsBreakdownType), nil
}

type SettlementsLegalEntityType string

const (
	SettlementsLegalEntityTypePartner  SettlementsLegalEntityType = "partner"
	SettlementsLegalEntityTypePlatform SettlementsLegalEntityType = "platform"
)

func (e *SettlementsLegalEntityType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SettlementsLegalEntityType(s)
	case string:
		*e = SettlementsLegalEntityType(s)
	default:
		return fmt.Errorf("unsupported scan type for SettlementsLegalEntityType: %T", src)
	}
	return nil
}

type NullSettlementsLegalEntityType struct {
	SettlementsLegalEntityType SettlementsLegalEntityType
	Valid                      bool // Valid is true if SettlementsLegalEntityType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSettlementsLegalEntityType) Scan(value interface{}) error {
	if value == nil {
		ns.SettlementsLegalEntityType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SettlementsLegalEntityType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSettlementsLegalEntityType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SettlementsLegalEntityType), nil
}

type SettlementsPartnerType string

const (
	SettlementsPartnerTypeRestaurant SettlementsPartnerType = "restaurant"
	SettlementsPartnerTypeCourier    SettlementsPartnerType = "courier"
)

func (e *SettlementsPartnerType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SettlementsPartnerType(s)
	case string:
		*e = SettlementsPartnerType(s)
	default:
		return fmt.Errorf("unsupported scan type for SettlementsPartnerType: %T", src)
	}
	return nil
}

type NullSettlementsPartnerType struct {
	SettlementsPartnerType SettlementsPartnerType
	Valid                  bool // Valid is true if SettlementsPartnerType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSettlementsPartnerType) Scan(value interface{}) error {
	if value == nil {
		ns.SettlementsPartnerType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SettlementsPartnerType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSettlementsPartnerType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SettlementsPartnerType), nil
}

type SettlementsBillingCycle struct {
	BillingCycleUuid   domain.BillingCycleUUID
	PartnerUuid        domain.LegalEntityUUID
	PartnerType        domain.PartnerType
	BillingCycleNumber int32
	Closed             bool
	Settled            bool
	StartDate          time.Time
	EndDate            *time.Time
}

type SettlementsBillingCycleOrder struct {
	BillingCycleUuid domain.BillingCycleUUID
	OrderUuid        models.OrderUUID
}

type SettlementsLegalEntity struct {
	LegalEntityUuid   domain.LegalEntityUUID
	LegalEntityType   models.LegalEntityType
	BusinessName      string
	Address           shared.Address
	TaxID             shared.TaxID
	BankAccountNumber string
	Currency          shared.Currency
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type SettlementsOrder struct {
	OrderUuid           models.OrderUUID
	RestaurantUuid      domain.LegalEntityUUID
	CourierUuid         domain.LegalEntityUUID
	Currency            shared.Currency
	CommissionNetAmount decimal.Decimal
	OrderedAt           time.Time
}

type SettlementsOrderBreakdown struct {
	OrderUuid     models.OrderUUID
	BreakdownType SettlementsBreakdownType
	NetAmount     decimal.Decimal
	TaxAmount     decimal.Decimal
	GrossAmount   decimal.Decimal
}

type SettlementsPartnerPlatformMapping struct {
	PartnerUuid        domain.LegalEntityUUID
	PlatformEntityUuid models.PlatformEntityUUID
}
