// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package dbmodels

import (
	"context"
	"time"

	"eats/backend/common/shared"
	"eats/backend/settlements/app/models"
	"eats/backend/settlements/domain"
	"github.com/shopspring/decimal"
)

const saveOrder = `-- name: SaveOrder :exec
INSERT INTO settlements.orders (order_uuid, restaurant_uuid, courier_uuid, currency, commission_net_amount, ordered_at)
VALUES (
           $1,
           $2, $3, $4,
           $5, $6
)
ON CONFLICT (order_uuid) DO NOTHING
`

type SaveOrderParams struct {
	OrderUuid           models.OrderUUID
	RestaurantUuid      domain.LegalEntityUUID
	CourierUuid         domain.LegalEntityUUID
	Currency            shared.Currency
	CommissionNetAmount decimal.Decimal
	OrderedAt           time.Time
}

func (q *Queries) SaveOrder(ctx context.Context, arg SaveOrderParams) error {
	_, err := q.db.Exec(ctx, saveOrder,
		arg.OrderUuid,
		arg.RestaurantUuid,
		arg.CourierUuid,
		arg.Currency,
		arg.CommissionNetAmount,
		arg.OrderedAt,
	)
	return err
}

const saveOrderBreakdown = `-- name: SaveOrderBreakdown :exec
INSERT INTO settlements.order_breakdowns (order_uuid, breakdown_type, net_amount, tax_amount, gross_amount)
VALUES (
           $1, $2,
           $3, $4, $5
)
ON CONFLICT (order_uuid, breakdown_type) DO NOTHING
`

type SaveOrderBreakdownParams struct {
	OrderUuid     models.OrderUUID
	BreakdownType SettlementsBreakdownType
	NetAmount     decimal.Decimal
	TaxAmount     decimal.Decimal
	GrossAmount   decimal.Decimal
}

func (q *Queries) SaveOrderBreakdown(ctx context.Context, arg SaveOrderBreakdownParams) error {
	_, err := q.db.Exec(ctx, saveOrderBreakdown,
		arg.OrderUuid,
		arg.BreakdownType,
		arg.NetAmount,
		arg.TaxAmount,
		arg.GrossAmount,
	)
	return err
}
