// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package http

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"eats/backend/common"
	"eats/backend/common/shared"
	"eats/backend/orders/app"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
	openapi_types "github.com/oapi-codegen/runtime/types"
	"github.com/shopspring/decimal"
)

// Defines values for ListMenuItemsParamsOrderBy.
const (
	NameAsc   ListMenuItemsParamsOrderBy = "name_asc"
	NameDesc  ListMenuItemsParamsOrderBy = "name_desc"
	PriceAsc  ListMenuItemsParamsOrderBy = "price_asc"
	PriceDesc ListMenuItemsParamsOrderBy = "price_desc"
	Relevance ListMenuItemsParamsOrderBy = "relevance"
)

// AcceptDelivery defines model for AcceptDelivery.
type AcceptDelivery struct {
	// OrderUuid UUID of an order
	OrderUuid OrderUUID `json:"order_uuid"`
}

// AcceptOrder defines model for AcceptOrder.
type AcceptOrder struct {
	// OrderUuid UUID of an order
	OrderUuid OrderUUID `json:"order_uuid"`
}

// Address defines model for Address.
type Address struct {
	// City City of the address
	City string `json:"city"`

	// CountryCode Country code in ISO 3166-1 alpha-2 format
	CountryCode CountryCode `json:"country_code"`

	// Line1 First line of the address
	Line1 string `json:"line1"`

	// Line2 Second line of the address
	Line2 string `json:"line2"`

	// PostalCode Postal code of the address
	PostalCode string `json:"postal_code"`
}

// CountryCode Country code in ISO 3166-1 alpha-2 format
type CountryCode = shared.CountryCode

// CourierOrder defines model for CourierOrder.
type CourierOrder struct {
	// AcceptedByCourierAt When the courier accepted the order
	AcceptedByCourierAt *time.Time   `json:"accepted_by_courier_at"`
	CourierUuid         *CourierUUID `json:"courier_uuid"`

	// CustomerUuid UUID of a customer
	CustomerUuid CustomerUUID `json:"customer_uuid"`

	// DeliveredAt When the order was delivered
	DeliveredAt        *time.Time `json:"delivered_at"`
	DeliveryAddress    Address    `json:"delivery_address"`
	ItemsSubtotalGross Decimal    `json:"items_subtotal_gross"`

	// OrderUuid UUID of an order
	OrderUuid OrderUUID `json:"order_uuid"`

	// OrderedAt When the order was placed
	OrderedAt time.Time `json:"ordered_at"`

	// PickedUpAt When the order was picked up
	PickedUpAt *time.Time `json:"picked_up_at"`

	// RestaurantConfirmedAt When the restaurant confirmed the order
	RestaurantConfirmedAt *time.Time `json:"restaurant_confirmed_at"`

	// RestaurantName Name of the restaurant
	RestaurantName string `json:"restaurant_name"`

	// RestaurantPreparedAt When the order was marked ready for pickup
	RestaurantPreparedAt *time.Time `json:"restaurant_prepared_at"`

	// RestaurantUuid UUID of a restaurant
	RestaurantUuid RestaurantUUID `json:"restaurant_uuid"`
}

// CourierUUID UUID of a courier
type CourierUUID = app.CourierUUID

// CreateQuoteRequest defines model for CreateQuoteRequest.
type CreateQuoteRequest struct {
	DeliveryAddress Address     `json:"delivery_address"`
	Items           []OrderItem `json:"items"`

	// RestaurantUuid UUID of a restaurant
	RestaurantUuid RestaurantUUID `json:"restaurant_uuid"`
}

// CreateQuoteResponse defines model for CreateQuoteResponse.
type CreateQuoteResponse struct {
	// Currency Currency code in ISO 4217 format
	Currency         Currency `json:"currency"`
	DeliveryFeeGross Decimal  `json:"delivery_fee_gross"`

	// ExpiresAt When the offer expires
	ExpiresAt          time.Time `json:"expires_at"`
	ItemsSubtotalGross Decimal   `json:"items_subtotal_gross"`

	// QuoteUuid UUID of an quote
	QuoteUuid       QuoteUUID `json:"quote_uuid"`
	ServiceFeeGross Decimal   `json:"service_fee_gross"`
	TotalGross      Decimal   `json:"total_gross"`
	TotalTax        Decimal   `json:"total_tax"`
}

// Currency Currency code in ISO 4217 format
type Currency = shared.Currency

// CustomerOrder defines model for CustomerOrder.
type CustomerOrder struct {
	CourierAcceptedAt *time.Time `json:"courier_accepted_at,omitempty"`

	// CourierUuid UUID of a courier
	CourierUuid *CourierUUID `json:"courier_uuid,omitempty"`

	// Currency Currency code in ISO 4217 format
	Currency           Currency   `json:"currency"`
	DeliveredAt        *time.Time `json:"delivered_at,omitempty"`
	DeliveryAddress    Address    `json:"delivery_address"`
	DeliveryFeeGross   Decimal    `json:"delivery_fee_gross"`
	ItemsSubtotalGross Decimal    `json:"items_subtotal_gross"`

	// OrderUuid UUID of an order
	OrderUuid OrderUUID `json:"order_uuid"`

	// OrderedAt When the order was placed
	OrderedAt             time.Time  `json:"ordered_at"`
	PickedUpAt            *time.Time `json:"picked_up_at,omitempty"`
	RestaurantConfirmedAt *time.Time `json:"restaurant_confirmed_at,omitempty"`
	RestaurantName        string     `json:"restaurant_name"`
	RestaurantPreparedAt  *time.Time `json:"restaurant_prepared_at,omitempty"`

	// RestaurantUuid UUID of a restaurant
	RestaurantUuid  RestaurantUUID `json:"restaurant_uuid"`
	ServiceFeeGross Decimal        `json:"service_fee_gross"`
	TotalGross      Decimal        `json:"total_gross"`
	TotalTax        Decimal        `json:"total_tax"`
}

// CustomerUUID UUID of a customer
type CustomerUUID = app.CustomerUUID

// Decimal defines model for Decimal.
type Decimal = decimal.Decimal

// ErrorDetails defines model for ErrorDetails.
type ErrorDetails struct {
	EntityId   *string `json:"entity_id,omitempty"`
	EntityType *string `json:"entity_type,omitempty"`
	ErrorSlug  string  `json:"error_slug"`
	Message    string  `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Details Detailed error information
	Details []ErrorDetails `json:"details"`

	// Message Human-readable error message
	Message string `json:"message"`

	// Slug Error slug
	Slug string `json:"slug"`
}

// MarkOrderReady defines model for MarkOrderReady.
type MarkOrderReady struct {
	// OrderUuid UUID of an order
	OrderUuid OrderUUID `json:"order_uuid"`
}

// MenuItem defines model for MenuItem.
type MenuItem struct {
	GrossPrice Decimal `json:"gross_price"`

	// Name Item name
	Name string `json:"name"`

	// Ordering Ordering index for display
	Ordering float32 `json:"ordering"`

	// Uuid UUID of a menu item
	Uuid MenuItemUUID `json:"uuid"`
}

// MenuItemUUID UUID of a menu item
type MenuItemUUID = app.RestaurantMenuItemUUID

// MenuItemWithRestaurant defines model for MenuItemWithRestaurant.
type MenuItemWithRestaurant struct {
	// Currency Currency code in ISO 4217 format
	Currency   Currency `json:"currency"`
	GrossPrice Decimal  `json:"gross_price"`

	// MenuItemName Name of the menu item
	MenuItemName string `json:"menu_item_name"`

	// MenuItemUuid UUID of a menu item
	MenuItemUuid MenuItemUUID `json:"menu_item_uuid"`

	// RestaurantName Name of the restaurant
	RestaurantName string `json:"restaurant_name"`

	// RestaurantUuid UUID of a restaurant
	RestaurantUuid RestaurantUUID `json:"restaurant_uuid"`
}

// OnboardRestaurant defines model for OnboardRestaurant.
type OnboardRestaurant struct {
	Address Address `json:"address"`

	// Currency Currency code in ISO 4217 format
	Currency Currency `json:"currency"`

	// Description Restaurant description
	Description string `json:"description"`

	// MenuItems Menu items for the restaurant
	MenuItems []MenuItem `json:"menu_items"`

	// Name Restaurant name
	Name string `json:"name"`
}

// OperatorUUID UUID of an operator
type OperatorUUID = common.UUID

// OrderItem defines model for OrderItem.
type OrderItem struct {
	// MenuItemUuid UUID of a menu item
	MenuItemUuid MenuItemUUID `json:"menu_item_uuid"`

	// Quantity Quantity of the item
	Quantity int `json:"quantity"`
}

// OrderUUID UUID of an order
type OrderUUID = app.OrderUUID

// PlaceOrder defines model for PlaceOrder.
type PlaceOrder struct {
	PaymentNonce string `json:"payment_nonce"`

	// QuoteUuid UUID of an quote
	QuoteUuid QuoteUUID `json:"quote_uuid"`
}

// QuoteUUID UUID of an quote
type QuoteUUID = app.QuoteUUID

// RegisterCourier defines model for RegisterCourier.
type RegisterCourier struct {
	// City City where courier operates
	City string `json:"city"`

	// Name Courier's full name
	Name string `json:"name"`

	// PhoneNumber Courier's phone number
	PhoneNumber string `json:"phone_number"`
}

// RegisterCourierResponse defines model for RegisterCourierResponse.
type RegisterCourierResponse struct {
	// CourierUuid UUID of a courier
	CourierUuid CourierUUID `json:"courier_uuid"`
}

// RegisterCustomer defines model for RegisterCustomer.
type RegisterCustomer struct {
	Address Address `json:"address"`

	// Email Customer's email address
	Email openapi_types.Email `json:"email"`

	// Name Customer's full name
	Name string `json:"name"`

	// PhoneNumber Customer's phone number
	PhoneNumber string `json:"phone_number"`
}

// RegisterCustomerResponse defines model for RegisterCustomerResponse.
type RegisterCustomerResponse struct {
	// CustomerUuid UUID of a customer
	CustomerUuid CustomerUUID `json:"customer_uuid"`
}

// ReportDelivery defines model for ReportDelivery.
type ReportDelivery struct {
	// OrderUuid UUID of an order
	OrderUuid OrderUUID `json:"order_uuid"`
}

// ReportPickup defines model for ReportPickup.
type ReportPickup struct {
	// OrderUuid UUID of an order
	OrderUuid OrderUUID `json:"order_uuid"`
}

// Restaurant defines model for Restaurant.
type Restaurant struct {
	Address Address `json:"address"`

	// Description Restaurant description
	Description string `json:"description"`

	// Name Restaurant name
	Name string `json:"name"`

	// Uuid UUID of a restaurant
	Uuid RestaurantUUID `json:"uuid"`
}

// RestaurantOrder defines model for RestaurantOrder.
type RestaurantOrder struct {
	// CourierAcceptedAt When the courier accepted the order
	CourierAcceptedAt *time.Time   `json:"courier_accepted_at"`
	CourierUuid       *CourierUUID `json:"courier_uuid"`

	// CustomerUuid UUID of a customer
	CustomerUuid CustomerUUID `json:"customer_uuid"`

	// DeliveredAt When the order was delivered
	DeliveredAt        *time.Time `json:"delivered_at"`
	ItemsSubtotalGross Decimal    `json:"items_subtotal_gross"`

	// OrderUuid UUID of an order
	OrderUuid OrderUUID `json:"order_uuid"`

	// OrderedAt When the order was placed
	OrderedAt time.Time `json:"ordered_at"`

	// PickedUpAt When the order was picked up
	PickedUpAt *time.Time `json:"picked_up_at"`

	// RestaurantConfirmedAt When the restaurant confirmed the order
	RestaurantConfirmedAt *time.Time `json:"restaurant_confirmed_at"`

	// RestaurantPreparedAt When the order was marked ready for pickup
	RestaurantPreparedAt *time.Time `json:"restaurant_prepared_at"`
}

// RestaurantUUID UUID of a restaurant
type RestaurantUUID = app.RestaurantUUID

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// Gone defines model for Gone.
type Gone = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// CourierAcceptDeliveryParams defines parameters for CourierAcceptDelivery.
type CourierAcceptDeliveryParams struct {
	// CourierUUID Courier UUID
	CourierUUID CourierUUID `json:"Courier-UUID"`
}

// CourierGetAvailableOrdersParams defines parameters for CourierGetAvailableOrders.
type CourierGetAvailableOrdersParams struct {
	// CourierUUID Courier UUID
	CourierUUID CourierUUID `json:"Courier-UUID"`
}

// CourierGetCurrentOrdersParams defines parameters for CourierGetCurrentOrders.
type CourierGetCurrentOrdersParams struct {
	// CourierUUID Courier UUID
	CourierUUID CourierUUID `json:"Courier-UUID"`
}

// CourierReportDeliveryParams defines parameters for CourierReportDelivery.
type CourierReportDeliveryParams struct {
	// CourierUUID Courier UUID
	CourierUUID CourierUUID `json:"Courier-UUID"`
}

// CourierReportPickupParams defines parameters for CourierReportPickup.
type CourierReportPickupParams struct {
	// CourierUUID Courier UUID
	CourierUUID CourierUUID `json:"Courier-UUID"`
}

// CustomerCreateQuoteParams defines parameters for CustomerCreateQuote.
type CustomerCreateQuoteParams struct {
	// CustomerUUID Customer UUID
	CustomerUUID CustomerUUID `json:"Customer-UUID"`
}

// CustomerGetOrdersParams defines parameters for CustomerGetOrders.
type CustomerGetOrdersParams struct {
	// CustomerUUID Customer UUID
	CustomerUUID CustomerUUID `json:"Customer-UUID"`
}

// CustomerPlaceOrderParams defines parameters for CustomerPlaceOrder.
type CustomerPlaceOrderParams struct {
	// CustomerUUID Customer UUID
	CustomerUUID CustomerUUID `json:"Customer-UUID"`
}

// CustomerListRestaurantsParams defines parameters for CustomerListRestaurants.
type CustomerListRestaurantsParams struct {
	// CustomerUUID Customer UUID
	CustomerUUID CustomerUUID `json:"Customer-UUID"`
}

// CustomerGetRestaurantMenuParams defines parameters for CustomerGetRestaurantMenu.
type CustomerGetRestaurantMenuParams struct {
	// CustomerUUID Customer UUID
	CustomerUUID CustomerUUID `json:"Customer-UUID"`
}

// RestaurantAcceptOrderParams defines parameters for RestaurantAcceptOrder.
type RestaurantAcceptOrderParams struct {
	// RestaurantUUID Restaurant UUID
	RestaurantUUID RestaurantUUID `json:"Restaurant-UUID"`
}

// RestaurantMarkOrderReadyForPickupParams defines parameters for RestaurantMarkOrderReadyForPickup.
type RestaurantMarkOrderReadyForPickupParams struct {
	// RestaurantUUID Restaurant UUID
	RestaurantUUID RestaurantUUID `json:"Restaurant-UUID"`
}

// OnboardRestaurantParams defines parameters for OnboardRestaurant.
type OnboardRestaurantParams struct {
	OperatorUUID OperatorUUID `json:"Operator-UUID"`
}

// RestaurantGetOrdersParams defines parameters for RestaurantGetOrders.
type RestaurantGetOrdersParams struct {
	// RestaurantUUID Restaurant UUID
	RestaurantUUID RestaurantUUID `json:"Restaurant-UUID"`
}

// ListMenuItemsParams defines parameters for ListMenuItems.
type ListMenuItemsParams struct {
	// RestaurantName Filter by restaurant name (case-insensitive partial match)
	RestaurantName *string `form:"restaurant_name,omitempty" json:"restaurant_name,omitempty"`

	// Search Full-text search across menu item names and restaurant names
	Search *string `form:"search,omitempty" json:"search,omitempty"`

	// OrderBy Order results by price, name, or relevance (when searching)
	OrderBy *ListMenuItemsParamsOrderBy `form:"order_by,omitempty" json:"order_by,omitempty"`
}

// ListMenuItemsParamsOrderBy defines parameters for ListMenuItems.
type ListMenuItemsParamsOrderBy string

// CourierAcceptDeliveryJSONRequestBody defines body for CourierAcceptDelivery for application/json ContentType.
type CourierAcceptDeliveryJSONRequestBody = AcceptDelivery

// CourierReportDeliveryJSONRequestBody defines body for CourierReportDelivery for application/json ContentType.
type CourierReportDeliveryJSONRequestBody = ReportDelivery

// CourierReportPickupJSONRequestBody defines body for CourierReportPickup for application/json ContentType.
type CourierReportPickupJSONRequestBody = ReportPickup

// CustomerCreateQuoteJSONRequestBody defines body for CustomerCreateQuote for application/json ContentType.
type CustomerCreateQuoteJSONRequestBody = CreateQuoteRequest

// CustomerPlaceOrderJSONRequestBody defines body for CustomerPlaceOrder for application/json ContentType.
type CustomerPlaceOrderJSONRequestBody = PlaceOrder

// RegisterCourierJSONRequestBody defines body for RegisterCourier for application/json ContentType.
type RegisterCourierJSONRequestBody = RegisterCourier

// RegisterCustomerJSONRequestBody defines body for RegisterCustomer for application/json ContentType.
type RegisterCustomerJSONRequestBody = RegisterCustomer

// RestaurantAcceptOrderJSONRequestBody defines body for RestaurantAcceptOrder for application/json ContentType.
type RestaurantAcceptOrderJSONRequestBody = AcceptOrder

// RestaurantMarkOrderReadyForPickupJSONRequestBody defines body for RestaurantMarkOrderReadyForPickup for application/json ContentType.
type RestaurantMarkOrderReadyForPickupJSONRequestBody = MarkOrderReady

// OnboardRestaurantJSONRequestBody defines body for OnboardRestaurant for application/json ContentType.
type OnboardRestaurantJSONRequestBody = OnboardRestaurant

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Courier accepts delivery job
	// (POST /orders/courier/accept-delivery)
	CourierAcceptDelivery(ctx echo.Context, params CourierAcceptDeliveryParams) error
	// List orders available for delivery
	// (GET /orders/courier/available-orders)
	CourierGetAvailableOrders(ctx echo.Context, params CourierGetAvailableOrdersParams) error
	// List current orders assigned to courier
	// (GET /orders/courier/current-orders)
	CourierGetCurrentOrders(ctx echo.Context, params CourierGetCurrentOrdersParams) error
	// Courier reports successful delivery
	// (POST /orders/courier/report-delivery)
	CourierReportDelivery(ctx echo.Context, params CourierReportDeliveryParams) error
	// Courier reports picking up an order
	// (POST /orders/courier/report-pickup)
	CourierReportPickup(ctx echo.Context, params CourierReportPickupParams) error
	// Create order quote
	// (POST /orders/customer/create-quote)
	CustomerCreateQuote(ctx echo.Context, params CustomerCreateQuoteParams) error
	// List customer orders
	// (GET /orders/customer/orders)
	CustomerGetOrders(ctx echo.Context, params CustomerGetOrdersParams) error
	// Place a new order using an order offer
	// (POST /orders/customer/place-order)
	CustomerPlaceOrder(ctx echo.Context, params CustomerPlaceOrderParams) error
	// List all restaurants
	// (GET /orders/customer/restaurants)
	CustomerListRestaurants(ctx echo.Context, params CustomerListRestaurantsParams) error
	// Get restaurant menu
	// (GET /orders/customer/{restaurant_uuid}/menu)
	CustomerGetRestaurantMenu(ctx echo.Context, restaurantUuid RestaurantUUID, params CustomerGetRestaurantMenuParams) error
	// Register a new courier
	// (POST /orders/register-courier)
	RegisterCourier(ctx echo.Context) error
	// Register a new customer
	// (POST /orders/register-customer)
	RegisterCustomer(ctx echo.Context) error
	// Restaurant accepts an order
	// (POST /orders/restaurant/accept-order)
	RestaurantAcceptOrder(ctx echo.Context, params RestaurantAcceptOrderParams) error
	// Restaurant marks order as ready for pickup
	// (POST /orders/restaurant/mark-order-ready-for-pickup)
	RestaurantMarkOrderReadyForPickup(ctx echo.Context, params RestaurantMarkOrderReadyForPickupParams) error
	// Onboard or replace a restaurant with full details
	// (PUT /orders/restaurant/onboard/{restaurant_uuid})
	OnboardRestaurant(ctx echo.Context, restaurantUuid RestaurantUUID, params OnboardRestaurantParams) error
	// List orders for restaurant
	// (GET /orders/restaurant/orders)
	RestaurantGetOrders(ctx echo.Context, params RestaurantGetOrdersParams) error
	// List all menu items with restaurant info
	// (GET /orders/restaurants/menu-items)
	ListMenuItems(ctx echo.Context, params ListMenuItemsParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// CourierAcceptDelivery converts echo context to params.
func (w *ServerInterfaceWrapper) CourierAcceptDelivery(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CourierAcceptDeliveryParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Courier-UUID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Courier-UUID")]; found {
		var CourierUUID CourierUUID
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Courier-UUID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Courier-UUID", valueList[0], &CourierUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Courier-UUID: %s", err))
		}

		params.CourierUUID = CourierUUID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Courier-UUID is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CourierAcceptDelivery(ctx, params)
	return err
}

// CourierGetAvailableOrders converts echo context to params.
func (w *ServerInterfaceWrapper) CourierGetAvailableOrders(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CourierGetAvailableOrdersParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Courier-UUID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Courier-UUID")]; found {
		var CourierUUID CourierUUID
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Courier-UUID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Courier-UUID", valueList[0], &CourierUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Courier-UUID: %s", err))
		}

		params.CourierUUID = CourierUUID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Courier-UUID is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CourierGetAvailableOrders(ctx, params)
	return err
}

// CourierGetCurrentOrders converts echo context to params.
func (w *ServerInterfaceWrapper) CourierGetCurrentOrders(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CourierGetCurrentOrdersParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Courier-UUID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Courier-UUID")]; found {
		var CourierUUID CourierUUID
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Courier-UUID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Courier-UUID", valueList[0], &CourierUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Courier-UUID: %s", err))
		}

		params.CourierUUID = CourierUUID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Courier-UUID is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CourierGetCurrentOrders(ctx, params)
	return err
}

// CourierReportDelivery converts echo context to params.
func (w *ServerInterfaceWrapper) CourierReportDelivery(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CourierReportDeliveryParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Courier-UUID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Courier-UUID")]; found {
		var CourierUUID CourierUUID
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Courier-UUID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Courier-UUID", valueList[0], &CourierUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Courier-UUID: %s", err))
		}

		params.CourierUUID = CourierUUID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Courier-UUID is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CourierReportDelivery(ctx, params)
	return err
}

// CourierReportPickup converts echo context to params.
func (w *ServerInterfaceWrapper) CourierReportPickup(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CourierReportPickupParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Courier-UUID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Courier-UUID")]; found {
		var CourierUUID CourierUUID
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Courier-UUID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Courier-UUID", valueList[0], &CourierUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Courier-UUID: %s", err))
		}

		params.CourierUUID = CourierUUID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Courier-UUID is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CourierReportPickup(ctx, params)
	return err
}

// CustomerCreateQuote converts echo context to params.
func (w *ServerInterfaceWrapper) CustomerCreateQuote(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CustomerCreateQuoteParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Customer-UUID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Customer-UUID")]; found {
		var CustomerUUID CustomerUUID
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Customer-UUID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Customer-UUID", valueList[0], &CustomerUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Customer-UUID: %s", err))
		}

		params.CustomerUUID = CustomerUUID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Customer-UUID is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CustomerCreateQuote(ctx, params)
	return err
}

// CustomerGetOrders converts echo context to params.
func (w *ServerInterfaceWrapper) CustomerGetOrders(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CustomerGetOrdersParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Customer-UUID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Customer-UUID")]; found {
		var CustomerUUID CustomerUUID
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Customer-UUID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Customer-UUID", valueList[0], &CustomerUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Customer-UUID: %s", err))
		}

		params.CustomerUUID = CustomerUUID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Customer-UUID is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CustomerGetOrders(ctx, params)
	return err
}

// CustomerPlaceOrder converts echo context to params.
func (w *ServerInterfaceWrapper) CustomerPlaceOrder(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CustomerPlaceOrderParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Customer-UUID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Customer-UUID")]; found {
		var CustomerUUID CustomerUUID
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Customer-UUID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Customer-UUID", valueList[0], &CustomerUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Customer-UUID: %s", err))
		}

		params.CustomerUUID = CustomerUUID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Customer-UUID is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CustomerPlaceOrder(ctx, params)
	return err
}

// CustomerListRestaurants converts echo context to params.
func (w *ServerInterfaceWrapper) CustomerListRestaurants(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CustomerListRestaurantsParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Customer-UUID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Customer-UUID")]; found {
		var CustomerUUID CustomerUUID
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Customer-UUID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Customer-UUID", valueList[0], &CustomerUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Customer-UUID: %s", err))
		}

		params.CustomerUUID = CustomerUUID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Customer-UUID is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CustomerListRestaurants(ctx, params)
	return err
}

// CustomerGetRestaurantMenu converts echo context to params.
func (w *ServerInterfaceWrapper) CustomerGetRestaurantMenu(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "restaurant_uuid" -------------
	var restaurantUuid RestaurantUUID

	err = runtime.BindStyledParameterWithOptions("simple", "restaurant_uuid", ctx.Param("restaurant_uuid"), &restaurantUuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter restaurant_uuid: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CustomerGetRestaurantMenuParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Customer-UUID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Customer-UUID")]; found {
		var CustomerUUID CustomerUUID
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Customer-UUID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Customer-UUID", valueList[0], &CustomerUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Customer-UUID: %s", err))
		}

		params.CustomerUUID = CustomerUUID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Customer-UUID is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CustomerGetRestaurantMenu(ctx, restaurantUuid, params)
	return err
}

// RegisterCourier converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterCourier(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RegisterCourier(ctx)
	return err
}

// RegisterCustomer converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterCustomer(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RegisterCustomer(ctx)
	return err
}

// RestaurantAcceptOrder converts echo context to params.
func (w *ServerInterfaceWrapper) RestaurantAcceptOrder(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params RestaurantAcceptOrderParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Restaurant-UUID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Restaurant-UUID")]; found {
		var RestaurantUUID RestaurantUUID
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Restaurant-UUID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Restaurant-UUID", valueList[0], &RestaurantUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Restaurant-UUID: %s", err))
		}

		params.RestaurantUUID = RestaurantUUID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Restaurant-UUID is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RestaurantAcceptOrder(ctx, params)
	return err
}

// RestaurantMarkOrderReadyForPickup converts echo context to params.
func (w *ServerInterfaceWrapper) RestaurantMarkOrderReadyForPickup(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params RestaurantMarkOrderReadyForPickupParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Restaurant-UUID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Restaurant-UUID")]; found {
		var RestaurantUUID RestaurantUUID
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Restaurant-UUID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Restaurant-UUID", valueList[0], &RestaurantUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Restaurant-UUID: %s", err))
		}

		params.RestaurantUUID = RestaurantUUID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Restaurant-UUID is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RestaurantMarkOrderReadyForPickup(ctx, params)
	return err
}

// OnboardRestaurant converts echo context to params.
func (w *ServerInterfaceWrapper) OnboardRestaurant(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "restaurant_uuid" -------------
	var restaurantUuid RestaurantUUID

	err = runtime.BindStyledParameterWithOptions("simple", "restaurant_uuid", ctx.Param("restaurant_uuid"), &restaurantUuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter restaurant_uuid: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params OnboardRestaurantParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Operator-UUID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Operator-UUID")]; found {
		var OperatorUUID OperatorUUID
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Operator-UUID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Operator-UUID", valueList[0], &OperatorUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Operator-UUID: %s", err))
		}

		params.OperatorUUID = OperatorUUID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Operator-UUID is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.OnboardRestaurant(ctx, restaurantUuid, params)
	return err
}

// RestaurantGetOrders converts echo context to params.
func (w *ServerInterfaceWrapper) RestaurantGetOrders(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params RestaurantGetOrdersParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Restaurant-UUID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Restaurant-UUID")]; found {
		var RestaurantUUID RestaurantUUID
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Restaurant-UUID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Restaurant-UUID", valueList[0], &RestaurantUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Restaurant-UUID: %s", err))
		}

		params.RestaurantUUID = RestaurantUUID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Restaurant-UUID is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RestaurantGetOrders(ctx, params)
	return err
}

// ListMenuItems converts echo context to params.
func (w *ServerInterfaceWrapper) ListMenuItems(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMenuItemsParams
	// ------------- Optional query parameter "restaurant_name" -------------

	err = runtime.BindQueryParameter("form", true, false, "restaurant_name", ctx.QueryParams(), &params.RestaurantName)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter restaurant_name: %s", err))
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, false, "search", ctx.QueryParams(), &params.Search)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter search: %s", err))
	}

	// ------------- Optional query parameter "order_by" -------------

	err = runtime.BindQueryParameter("form", true, false, "order_by", ctx.QueryParams(), &params.OrderBy)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter order_by: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListMenuItems(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/orders/courier/accept-delivery", wrapper.CourierAcceptDelivery)
	router.GET(baseURL+"/orders/courier/available-orders", wrapper.CourierGetAvailableOrders)
	router.GET(baseURL+"/orders/courier/current-orders", wrapper.CourierGetCurrentOrders)
	router.POST(baseURL+"/orders/courier/report-delivery", wrapper.CourierReportDelivery)
	router.POST(baseURL+"/orders/courier/report-pickup", wrapper.CourierReportPickup)
	router.POST(baseURL+"/orders/customer/create-quote", wrapper.CustomerCreateQuote)
	router.GET(baseURL+"/orders/customer/orders", wrapper.CustomerGetOrders)
	router.POST(baseURL+"/orders/customer/place-order", wrapper.CustomerPlaceOrder)
	router.GET(baseURL+"/orders/customer/restaurants", wrapper.CustomerListRestaurants)
	router.GET(baseURL+"/orders/customer/:restaurant_uuid/menu", wrapper.CustomerGetRestaurantMenu)
	router.POST(baseURL+"/orders/register-courier", wrapper.RegisterCourier)
	router.POST(baseURL+"/orders/register-customer", wrapper.RegisterCustomer)
	router.POST(baseURL+"/orders/restaurant/accept-order", wrapper.RestaurantAcceptOrder)
	router.POST(baseURL+"/orders/restaurant/mark-order-ready-for-pickup", wrapper.RestaurantMarkOrderReadyForPickup)
	router.PUT(baseURL+"/orders/restaurant/onboard/:restaurant_uuid", wrapper.OnboardRestaurant)
	router.GET(baseURL+"/orders/restaurant/orders", wrapper.RestaurantGetOrders)
	router.GET(baseURL+"/orders/restaurants/menu-items", wrapper.ListMenuItems)

}

type BadRequestJSONResponse ErrorResponse

type ConflictJSONResponse ErrorResponse

type ForbiddenJSONResponse ErrorResponse

type GoneJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type CourierAcceptDeliveryRequestObject struct {
	Params CourierAcceptDeliveryParams
	Body   *CourierAcceptDeliveryJSONRequestBody
}

type CourierAcceptDeliveryResponseObject interface {
	VisitCourierAcceptDeliveryResponse(w http.ResponseWriter) error
}

type CourierAcceptDelivery202Response struct {
}

func (response CourierAcceptDelivery202Response) VisitCourierAcceptDeliveryResponse(w http.ResponseWriter) error {
	w.WriteHeader(202)
	return nil
}

type CourierAcceptDelivery400JSONResponse struct{ BadRequestJSONResponse }

func (response CourierAcceptDelivery400JSONResponse) VisitCourierAcceptDeliveryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CourierAcceptDelivery401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CourierAcceptDelivery401JSONResponse) VisitCourierAcceptDeliveryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CourierAcceptDelivery403JSONResponse struct{ ForbiddenJSONResponse }

func (response CourierAcceptDelivery403JSONResponse) VisitCourierAcceptDeliveryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CourierAcceptDelivery404JSONResponse struct{ NotFoundJSONResponse }

func (response CourierAcceptDelivery404JSONResponse) VisitCourierAcceptDeliveryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CourierAcceptDelivery409JSONResponse struct{ ConflictJSONResponse }

func (response CourierAcceptDelivery409JSONResponse) VisitCourierAcceptDeliveryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CourierGetAvailableOrdersRequestObject struct {
	Params CourierGetAvailableOrdersParams
}

type CourierGetAvailableOrdersResponseObject interface {
	VisitCourierGetAvailableOrdersResponse(w http.ResponseWriter) error
}

type CourierGetAvailableOrders200JSONResponse struct {
	Orders []CourierOrder `json:"orders"`
}

func (response CourierGetAvailableOrders200JSONResponse) VisitCourierGetAvailableOrdersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CourierGetAvailableOrders401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CourierGetAvailableOrders401JSONResponse) VisitCourierGetAvailableOrdersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CourierGetCurrentOrdersRequestObject struct {
	Params CourierGetCurrentOrdersParams
}

type CourierGetCurrentOrdersResponseObject interface {
	VisitCourierGetCurrentOrdersResponse(w http.ResponseWriter) error
}

type CourierGetCurrentOrders200JSONResponse struct {
	Orders []CourierOrder `json:"orders"`
}

func (response CourierGetCurrentOrders200JSONResponse) VisitCourierGetCurrentOrdersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CourierGetCurrentOrders401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CourierGetCurrentOrders401JSONResponse) VisitCourierGetCurrentOrdersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CourierReportDeliveryRequestObject struct {
	Params CourierReportDeliveryParams
	Body   *CourierReportDeliveryJSONRequestBody
}

type CourierReportDeliveryResponseObject interface {
	VisitCourierReportDeliveryResponse(w http.ResponseWriter) error
}

type CourierReportDelivery202Response struct {
}

func (response CourierReportDelivery202Response) VisitCourierReportDeliveryResponse(w http.ResponseWriter) error {
	w.WriteHeader(202)
	return nil
}

type CourierReportDelivery400JSONResponse struct{ BadRequestJSONResponse }

func (response CourierReportDelivery400JSONResponse) VisitCourierReportDeliveryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CourierReportDelivery401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CourierReportDelivery401JSONResponse) VisitCourierReportDeliveryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CourierReportDelivery403JSONResponse struct{ ForbiddenJSONResponse }

func (response CourierReportDelivery403JSONResponse) VisitCourierReportDeliveryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CourierReportDelivery404JSONResponse struct{ NotFoundJSONResponse }

func (response CourierReportDelivery404JSONResponse) VisitCourierReportDeliveryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CourierReportPickupRequestObject struct {
	Params CourierReportPickupParams
	Body   *CourierReportPickupJSONRequestBody
}

type CourierReportPickupResponseObject interface {
	VisitCourierReportPickupResponse(w http.ResponseWriter) error
}

type CourierReportPickup202Response struct {
}

func (response CourierReportPickup202Response) VisitCourierReportPickupResponse(w http.ResponseWriter) error {
	w.WriteHeader(202)
	return nil
}

type CourierReportPickup400JSONResponse struct{ BadRequestJSONResponse }

func (response CourierReportPickup400JSONResponse) VisitCourierReportPickupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CourierReportPickup401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CourierReportPickup401JSONResponse) VisitCourierReportPickupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CourierReportPickup403JSONResponse struct{ ForbiddenJSONResponse }

func (response CourierReportPickup403JSONResponse) VisitCourierReportPickupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CourierReportPickup404JSONResponse struct{ NotFoundJSONResponse }

func (response CourierReportPickup404JSONResponse) VisitCourierReportPickupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CustomerCreateQuoteRequestObject struct {
	Params CustomerCreateQuoteParams
	Body   *CustomerCreateQuoteJSONRequestBody
}

type CustomerCreateQuoteResponseObject interface {
	VisitCustomerCreateQuoteResponse(w http.ResponseWriter) error
}

type CustomerCreateQuote201JSONResponse CreateQuoteResponse

func (response CustomerCreateQuote201JSONResponse) VisitCustomerCreateQuoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CustomerCreateQuote400JSONResponse struct{ BadRequestJSONResponse }

func (response CustomerCreateQuote400JSONResponse) VisitCustomerCreateQuoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CustomerCreateQuote401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CustomerCreateQuote401JSONResponse) VisitCustomerCreateQuoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CustomerCreateQuote403JSONResponse struct{ ForbiddenJSONResponse }

func (response CustomerCreateQuote403JSONResponse) VisitCustomerCreateQuoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CustomerCreateQuote404JSONResponse struct{ NotFoundJSONResponse }

func (response CustomerCreateQuote404JSONResponse) VisitCustomerCreateQuoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CustomerCreateQuote410JSONResponse struct{ GoneJSONResponse }

func (response CustomerCreateQuote410JSONResponse) VisitCustomerCreateQuoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(410)

	return json.NewEncoder(w).Encode(response)
}

type CustomerGetOrdersRequestObject struct {
	Params CustomerGetOrdersParams
}

type CustomerGetOrdersResponseObject interface {
	VisitCustomerGetOrdersResponse(w http.ResponseWriter) error
}

type CustomerGetOrders200JSONResponse struct {
	Orders []CustomerOrder `json:"orders"`
}

func (response CustomerGetOrders200JSONResponse) VisitCustomerGetOrdersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CustomerGetOrders400JSONResponse struct{ BadRequestJSONResponse }

func (response CustomerGetOrders400JSONResponse) VisitCustomerGetOrdersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CustomerGetOrders401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CustomerGetOrders401JSONResponse) VisitCustomerGetOrdersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CustomerGetOrders403JSONResponse struct{ ForbiddenJSONResponse }

func (response CustomerGetOrders403JSONResponse) VisitCustomerGetOrdersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CustomerGetOrders404JSONResponse struct{ NotFoundJSONResponse }

func (response CustomerGetOrders404JSONResponse) VisitCustomerGetOrdersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CustomerGetOrders410JSONResponse struct{ GoneJSONResponse }

func (response CustomerGetOrders410JSONResponse) VisitCustomerGetOrdersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(410)

	return json.NewEncoder(w).Encode(response)
}

type CustomerPlaceOrderRequestObject struct {
	Params CustomerPlaceOrderParams
	Body   *CustomerPlaceOrderJSONRequestBody
}

type CustomerPlaceOrderResponseObject interface {
	VisitCustomerPlaceOrderResponse(w http.ResponseWriter) error
}

type CustomerPlaceOrder201JSONResponse CustomerOrder

func (response CustomerPlaceOrder201JSONResponse) VisitCustomerPlaceOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CustomerPlaceOrder400JSONResponse struct{ BadRequestJSONResponse }

func (response CustomerPlaceOrder400JSONResponse) VisitCustomerPlaceOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CustomerPlaceOrder401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CustomerPlaceOrder401JSONResponse) VisitCustomerPlaceOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CustomerPlaceOrder403JSONResponse struct{ ForbiddenJSONResponse }

func (response CustomerPlaceOrder403JSONResponse) VisitCustomerPlaceOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CustomerPlaceOrder404JSONResponse struct{ NotFoundJSONResponse }

func (response CustomerPlaceOrder404JSONResponse) VisitCustomerPlaceOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CustomerPlaceOrder410JSONResponse struct{ GoneJSONResponse }

func (response CustomerPlaceOrder410JSONResponse) VisitCustomerPlaceOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(410)

	return json.NewEncoder(w).Encode(response)
}

type CustomerListRestaurantsRequestObject struct {
	Params CustomerListRestaurantsParams
}

type CustomerListRestaurantsResponseObject interface {
	VisitCustomerListRestaurantsResponse(w http.ResponseWriter) error
}

type CustomerListRestaurants200JSONResponse struct {
	Restaurants []Restaurant `json:"restaurants"`
}

func (response CustomerListRestaurants200JSONResponse) VisitCustomerListRestaurantsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CustomerListRestaurants401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CustomerListRestaurants401JSONResponse) VisitCustomerListRestaurantsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CustomerGetRestaurantMenuRequestObject struct {
	RestaurantUuid RestaurantUUID `json:"restaurant_uuid"`
	Params         CustomerGetRestaurantMenuParams
}

type CustomerGetRestaurantMenuResponseObject interface {
	VisitCustomerGetRestaurantMenuResponse(w http.ResponseWriter) error
}

type CustomerGetRestaurantMenu200JSONResponse struct {
	Address Address `json:"address"`

	// Currency Currency code in ISO 4217 format
	Currency       Currency   `json:"currency"`
	Description    string     `json:"description"`
	Items          []MenuItem `json:"items"`
	RestaurantName string     `json:"restaurant_name"`

	// RestaurantUuid UUID of a restaurant
	RestaurantUuid RestaurantUUID `json:"restaurant_uuid"`
}

func (response CustomerGetRestaurantMenu200JSONResponse) VisitCustomerGetRestaurantMenuResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CustomerGetRestaurantMenu401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CustomerGetRestaurantMenu401JSONResponse) VisitCustomerGetRestaurantMenuResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CustomerGetRestaurantMenu404JSONResponse struct{ NotFoundJSONResponse }

func (response CustomerGetRestaurantMenu404JSONResponse) VisitCustomerGetRestaurantMenuResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RegisterCourierRequestObject struct {
	Body *RegisterCourierJSONRequestBody
}

type RegisterCourierResponseObject interface {
	VisitRegisterCourierResponse(w http.ResponseWriter) error
}

type RegisterCourier201JSONResponse RegisterCourierResponse

func (response RegisterCourier201JSONResponse) VisitRegisterCourierResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type RegisterCourier400JSONResponse struct{ BadRequestJSONResponse }

func (response RegisterCourier400JSONResponse) VisitRegisterCourierResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RegisterCustomerRequestObject struct {
	Body *RegisterCustomerJSONRequestBody
}

type RegisterCustomerResponseObject interface {
	VisitRegisterCustomerResponse(w http.ResponseWriter) error
}

type RegisterCustomer201JSONResponse RegisterCustomerResponse

func (response RegisterCustomer201JSONResponse) VisitRegisterCustomerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type RegisterCustomer400JSONResponse struct{ BadRequestJSONResponse }

func (response RegisterCustomer400JSONResponse) VisitRegisterCustomerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RegisterCustomer409JSONResponse ErrorResponse

func (response RegisterCustomer409JSONResponse) VisitRegisterCustomerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type RestaurantAcceptOrderRequestObject struct {
	Params RestaurantAcceptOrderParams
	Body   *RestaurantAcceptOrderJSONRequestBody
}

type RestaurantAcceptOrderResponseObject interface {
	VisitRestaurantAcceptOrderResponse(w http.ResponseWriter) error
}

type RestaurantAcceptOrder202Response struct {
}

func (response RestaurantAcceptOrder202Response) VisitRestaurantAcceptOrderResponse(w http.ResponseWriter) error {
	w.WriteHeader(202)
	return nil
}

type RestaurantAcceptOrder400JSONResponse struct{ BadRequestJSONResponse }

func (response RestaurantAcceptOrder400JSONResponse) VisitRestaurantAcceptOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RestaurantAcceptOrder401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RestaurantAcceptOrder401JSONResponse) VisitRestaurantAcceptOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type RestaurantAcceptOrder403JSONResponse struct{ ForbiddenJSONResponse }

func (response RestaurantAcceptOrder403JSONResponse) VisitRestaurantAcceptOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type RestaurantAcceptOrder404JSONResponse struct{ NotFoundJSONResponse }

func (response RestaurantAcceptOrder404JSONResponse) VisitRestaurantAcceptOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RestaurantMarkOrderReadyForPickupRequestObject struct {
	Params RestaurantMarkOrderReadyForPickupParams
	Body   *RestaurantMarkOrderReadyForPickupJSONRequestBody
}

type RestaurantMarkOrderReadyForPickupResponseObject interface {
	VisitRestaurantMarkOrderReadyForPickupResponse(w http.ResponseWriter) error
}

type RestaurantMarkOrderReadyForPickup202Response struct {
}

func (response RestaurantMarkOrderReadyForPickup202Response) VisitRestaurantMarkOrderReadyForPickupResponse(w http.ResponseWriter) error {
	w.WriteHeader(202)
	return nil
}

type RestaurantMarkOrderReadyForPickup400JSONResponse struct{ BadRequestJSONResponse }

func (response RestaurantMarkOrderReadyForPickup400JSONResponse) VisitRestaurantMarkOrderReadyForPickupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RestaurantMarkOrderReadyForPickup401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RestaurantMarkOrderReadyForPickup401JSONResponse) VisitRestaurantMarkOrderReadyForPickupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type RestaurantMarkOrderReadyForPickup403JSONResponse struct{ ForbiddenJSONResponse }

func (response RestaurantMarkOrderReadyForPickup403JSONResponse) VisitRestaurantMarkOrderReadyForPickupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type RestaurantMarkOrderReadyForPickup404JSONResponse struct{ NotFoundJSONResponse }

func (response RestaurantMarkOrderReadyForPickup404JSONResponse) VisitRestaurantMarkOrderReadyForPickupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type OnboardRestaurantRequestObject struct {
	RestaurantUuid RestaurantUUID `json:"restaurant_uuid"`
	Params         OnboardRestaurantParams
	Body           *OnboardRestaurantJSONRequestBody
}

type OnboardRestaurantResponseObject interface {
	VisitOnboardRestaurantResponse(w http.ResponseWriter) error
}

type OnboardRestaurant204Response struct {
}

func (response OnboardRestaurant204Response) VisitOnboardRestaurantResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type OnboardRestaurant400JSONResponse struct{ BadRequestJSONResponse }

func (response OnboardRestaurant400JSONResponse) VisitOnboardRestaurantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type OnboardRestaurant401JSONResponse struct{ UnauthorizedJSONResponse }

func (response OnboardRestaurant401JSONResponse) VisitOnboardRestaurantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type OnboardRestaurant403JSONResponse struct{ ForbiddenJSONResponse }

func (response OnboardRestaurant403JSONResponse) VisitOnboardRestaurantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type RestaurantGetOrdersRequestObject struct {
	Params RestaurantGetOrdersParams
}

type RestaurantGetOrdersResponseObject interface {
	VisitRestaurantGetOrdersResponse(w http.ResponseWriter) error
}

type RestaurantGetOrders200JSONResponse struct {
	Orders []RestaurantOrder `json:"orders"`
}

func (response RestaurantGetOrders200JSONResponse) VisitRestaurantGetOrdersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RestaurantGetOrders401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RestaurantGetOrders401JSONResponse) VisitRestaurantGetOrdersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListMenuItemsRequestObject struct {
	Params ListMenuItemsParams
}

type ListMenuItemsResponseObject interface {
	VisitListMenuItemsResponse(w http.ResponseWriter) error
}

type ListMenuItems200JSONResponse []MenuItemWithRestaurant

func (response ListMenuItems200JSONResponse) VisitListMenuItemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Courier accepts delivery job
	// (POST /orders/courier/accept-delivery)
	CourierAcceptDelivery(ctx context.Context, request CourierAcceptDeliveryRequestObject) (CourierAcceptDeliveryResponseObject, error)
	// List orders available for delivery
	// (GET /orders/courier/available-orders)
	CourierGetAvailableOrders(ctx context.Context, request CourierGetAvailableOrdersRequestObject) (CourierGetAvailableOrdersResponseObject, error)
	// List current orders assigned to courier
	// (GET /orders/courier/current-orders)
	CourierGetCurrentOrders(ctx context.Context, request CourierGetCurrentOrdersRequestObject) (CourierGetCurrentOrdersResponseObject, error)
	// Courier reports successful delivery
	// (POST /orders/courier/report-delivery)
	CourierReportDelivery(ctx context.Context, request CourierReportDeliveryRequestObject) (CourierReportDeliveryResponseObject, error)
	// Courier reports picking up an order
	// (POST /orders/courier/report-pickup)
	CourierReportPickup(ctx context.Context, request CourierReportPickupRequestObject) (CourierReportPickupResponseObject, error)
	// Create order quote
	// (POST /orders/customer/create-quote)
	CustomerCreateQuote(ctx context.Context, request CustomerCreateQuoteRequestObject) (CustomerCreateQuoteResponseObject, error)
	// List customer orders
	// (GET /orders/customer/orders)
	CustomerGetOrders(ctx context.Context, request CustomerGetOrdersRequestObject) (CustomerGetOrdersResponseObject, error)
	// Place a new order using an order offer
	// (POST /orders/customer/place-order)
	CustomerPlaceOrder(ctx context.Context, request CustomerPlaceOrderRequestObject) (CustomerPlaceOrderResponseObject, error)
	// List all restaurants
	// (GET /orders/customer/restaurants)
	CustomerListRestaurants(ctx context.Context, request CustomerListRestaurantsRequestObject) (CustomerListRestaurantsResponseObject, error)
	// Get restaurant menu
	// (GET /orders/customer/{restaurant_uuid}/menu)
	CustomerGetRestaurantMenu(ctx context.Context, request CustomerGetRestaurantMenuRequestObject) (CustomerGetRestaurantMenuResponseObject, error)
	// Register a new courier
	// (POST /orders/register-courier)
	RegisterCourier(ctx context.Context, request RegisterCourierRequestObject) (RegisterCourierResponseObject, error)
	// Register a new customer
	// (POST /orders/register-customer)
	RegisterCustomer(ctx context.Context, request RegisterCustomerRequestObject) (RegisterCustomerResponseObject, error)
	// Restaurant accepts an order
	// (POST /orders/restaurant/accept-order)
	RestaurantAcceptOrder(ctx context.Context, request RestaurantAcceptOrderRequestObject) (RestaurantAcceptOrderResponseObject, error)
	// Restaurant marks order as ready for pickup
	// (POST /orders/restaurant/mark-order-ready-for-pickup)
	RestaurantMarkOrderReadyForPickup(ctx context.Context, request RestaurantMarkOrderReadyForPickupRequestObject) (RestaurantMarkOrderReadyForPickupResponseObject, error)
	// Onboard or replace a restaurant with full details
	// (PUT /orders/restaurant/onboard/{restaurant_uuid})
	OnboardRestaurant(ctx context.Context, request OnboardRestaurantRequestObject) (OnboardRestaurantResponseObject, error)
	// List orders for restaurant
	// (GET /orders/restaurant/orders)
	RestaurantGetOrders(ctx context.Context, request RestaurantGetOrdersRequestObject) (RestaurantGetOrdersResponseObject, error)
	// List all menu items with restaurant info
	// (GET /orders/restaurants/menu-items)
	ListMenuItems(ctx context.Context, request ListMenuItemsRequestObject) (ListMenuItemsResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// CourierAcceptDelivery operation middleware
func (sh *strictHandler) CourierAcceptDelivery(ctx echo.Context, params CourierAcceptDeliveryParams) error {
	var request CourierAcceptDeliveryRequestObject

	request.Params = params

	var body CourierAcceptDeliveryJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CourierAcceptDelivery(ctx.Request().Context(), request.(CourierAcceptDeliveryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CourierAcceptDelivery")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CourierAcceptDeliveryResponseObject); ok {
		return validResponse.VisitCourierAcceptDeliveryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CourierGetAvailableOrders operation middleware
func (sh *strictHandler) CourierGetAvailableOrders(ctx echo.Context, params CourierGetAvailableOrdersParams) error {
	var request CourierGetAvailableOrdersRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CourierGetAvailableOrders(ctx.Request().Context(), request.(CourierGetAvailableOrdersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CourierGetAvailableOrders")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CourierGetAvailableOrdersResponseObject); ok {
		return validResponse.VisitCourierGetAvailableOrdersResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CourierGetCurrentOrders operation middleware
func (sh *strictHandler) CourierGetCurrentOrders(ctx echo.Context, params CourierGetCurrentOrdersParams) error {
	var request CourierGetCurrentOrdersRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CourierGetCurrentOrders(ctx.Request().Context(), request.(CourierGetCurrentOrdersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CourierGetCurrentOrders")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CourierGetCurrentOrdersResponseObject); ok {
		return validResponse.VisitCourierGetCurrentOrdersResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CourierReportDelivery operation middleware
func (sh *strictHandler) CourierReportDelivery(ctx echo.Context, params CourierReportDeliveryParams) error {
	var request CourierReportDeliveryRequestObject

	request.Params = params

	var body CourierReportDeliveryJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CourierReportDelivery(ctx.Request().Context(), request.(CourierReportDeliveryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CourierReportDelivery")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CourierReportDeliveryResponseObject); ok {
		return validResponse.VisitCourierReportDeliveryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CourierReportPickup operation middleware
func (sh *strictHandler) CourierReportPickup(ctx echo.Context, params CourierReportPickupParams) error {
	var request CourierReportPickupRequestObject

	request.Params = params

	var body CourierReportPickupJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CourierReportPickup(ctx.Request().Context(), request.(CourierReportPickupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CourierReportPickup")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CourierReportPickupResponseObject); ok {
		return validResponse.VisitCourierReportPickupResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CustomerCreateQuote operation middleware
func (sh *strictHandler) CustomerCreateQuote(ctx echo.Context, params CustomerCreateQuoteParams) error {
	var request CustomerCreateQuoteRequestObject

	request.Params = params

	var body CustomerCreateQuoteJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CustomerCreateQuote(ctx.Request().Context(), request.(CustomerCreateQuoteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CustomerCreateQuote")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CustomerCreateQuoteResponseObject); ok {
		return validResponse.VisitCustomerCreateQuoteResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CustomerGetOrders operation middleware
func (sh *strictHandler) CustomerGetOrders(ctx echo.Context, params CustomerGetOrdersParams) error {
	var request CustomerGetOrdersRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CustomerGetOrders(ctx.Request().Context(), request.(CustomerGetOrdersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CustomerGetOrders")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CustomerGetOrdersResponseObject); ok {
		return validResponse.VisitCustomerGetOrdersResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CustomerPlaceOrder operation middleware
func (sh *strictHandler) CustomerPlaceOrder(ctx echo.Context, params CustomerPlaceOrderParams) error {
	var request CustomerPlaceOrderRequestObject

	request.Params = params

	var body CustomerPlaceOrderJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CustomerPlaceOrder(ctx.Request().Context(), request.(CustomerPlaceOrderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CustomerPlaceOrder")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CustomerPlaceOrderResponseObject); ok {
		return validResponse.VisitCustomerPlaceOrderResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CustomerListRestaurants operation middleware
func (sh *strictHandler) CustomerListRestaurants(ctx echo.Context, params CustomerListRestaurantsParams) error {
	var request CustomerListRestaurantsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CustomerListRestaurants(ctx.Request().Context(), request.(CustomerListRestaurantsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CustomerListRestaurants")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CustomerListRestaurantsResponseObject); ok {
		return validResponse.VisitCustomerListRestaurantsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CustomerGetRestaurantMenu operation middleware
func (sh *strictHandler) CustomerGetRestaurantMenu(ctx echo.Context, restaurantUuid RestaurantUUID, params CustomerGetRestaurantMenuParams) error {
	var request CustomerGetRestaurantMenuRequestObject

	request.RestaurantUuid = restaurantUuid
	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CustomerGetRestaurantMenu(ctx.Request().Context(), request.(CustomerGetRestaurantMenuRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CustomerGetRestaurantMenu")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CustomerGetRestaurantMenuResponseObject); ok {
		return validResponse.VisitCustomerGetRestaurantMenuResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RegisterCourier operation middleware
func (sh *strictHandler) RegisterCourier(ctx echo.Context) error {
	var request RegisterCourierRequestObject

	var body RegisterCourierJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterCourier(ctx.Request().Context(), request.(RegisterCourierRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterCourier")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RegisterCourierResponseObject); ok {
		return validResponse.VisitRegisterCourierResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RegisterCustomer operation middleware
func (sh *strictHandler) RegisterCustomer(ctx echo.Context) error {
	var request RegisterCustomerRequestObject

	var body RegisterCustomerJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterCustomer(ctx.Request().Context(), request.(RegisterCustomerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterCustomer")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RegisterCustomerResponseObject); ok {
		return validResponse.VisitRegisterCustomerResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RestaurantAcceptOrder operation middleware
func (sh *strictHandler) RestaurantAcceptOrder(ctx echo.Context, params RestaurantAcceptOrderParams) error {
	var request RestaurantAcceptOrderRequestObject

	request.Params = params

	var body RestaurantAcceptOrderJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RestaurantAcceptOrder(ctx.Request().Context(), request.(RestaurantAcceptOrderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RestaurantAcceptOrder")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RestaurantAcceptOrderResponseObject); ok {
		return validResponse.VisitRestaurantAcceptOrderResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RestaurantMarkOrderReadyForPickup operation middleware
func (sh *strictHandler) RestaurantMarkOrderReadyForPickup(ctx echo.Context, params RestaurantMarkOrderReadyForPickupParams) error {
	var request RestaurantMarkOrderReadyForPickupRequestObject

	request.Params = params

	var body RestaurantMarkOrderReadyForPickupJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RestaurantMarkOrderReadyForPickup(ctx.Request().Context(), request.(RestaurantMarkOrderReadyForPickupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RestaurantMarkOrderReadyForPickup")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RestaurantMarkOrderReadyForPickupResponseObject); ok {
		return validResponse.VisitRestaurantMarkOrderReadyForPickupResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// OnboardRestaurant operation middleware
func (sh *strictHandler) OnboardRestaurant(ctx echo.Context, restaurantUuid RestaurantUUID, params OnboardRestaurantParams) error {
	var request OnboardRestaurantRequestObject

	request.RestaurantUuid = restaurantUuid
	request.Params = params

	var body OnboardRestaurantJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.OnboardRestaurant(ctx.Request().Context(), request.(OnboardRestaurantRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "OnboardRestaurant")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(OnboardRestaurantResponseObject); ok {
		return validResponse.VisitOnboardRestaurantResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RestaurantGetOrders operation middleware
func (sh *strictHandler) RestaurantGetOrders(ctx echo.Context, params RestaurantGetOrdersParams) error {
	var request RestaurantGetOrdersRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RestaurantGetOrders(ctx.Request().Context(), request.(RestaurantGetOrdersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RestaurantGetOrders")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RestaurantGetOrdersResponseObject); ok {
		return validResponse.VisitRestaurantGetOrdersResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListMenuItems operation middleware
func (sh *strictHandler) ListMenuItems(ctx echo.Context, params ListMenuItemsParams) error {
	var request ListMenuItemsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListMenuItems(ctx.Request().Context(), request.(ListMenuItemsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListMenuItems")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListMenuItemsResponseObject); ok {
		return validResponse.VisitListMenuItemsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
