// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"eats/backend/common"
	"eats/backend/common/shared"
	"eats/backend/settlements/app/models"
	"eats/backend/settlements/domain"

	"github.com/oapi-codegen/runtime"
)

// Address defines model for Address.
type Address struct {
	// City City name
	City string `json:"city"`

	// CountryCode ISO 3166-1 alpha-2 country code
	CountryCode shared.CountryCode `json:"country_code"`

	// Line1 First address line
	Line1 string `json:"line1"`

	// Line2 Second address line
	Line2 string `json:"line2"`

	// PostalCode Postal code
	PostalCode string `json:"postal_code"`
}

// BillingCycle defines model for BillingCycle.
type BillingCycle struct {
	// BillingCycleNumber Billing cycle number
	BillingCycleNumber int `json:"billing_cycle_number"`

	// BillingCycleUuid UUID of a billing cycle
	BillingCycleUuid BillingCycleUUID `json:"billing_cycle_uuid"`

	// Closed Whether the billing cycle is closed
	Closed bool `json:"closed"`

	// EndDate End date of the billing cycle (null if not closed)
	EndDate *time.Time `json:"end_date"`

	// PartnerUuid UUID of a legal entity (partner)
	PartnerUuid LegalEntityUUID `json:"partner_uuid"`
	Settled     bool            `json:"settled"`

	// StartDate Start date of the billing cycle
	StartDate time.Time `json:"start_date"`
}

// BillingCycleUUID UUID of a billing cycle
type BillingCycleUUID = domain.BillingCycleUUID

// CreatePlatformEntity defines model for CreatePlatformEntity.
type CreatePlatformEntity struct {
	Address Address `json:"address"`

	// BankAccountIban Bank account IBAN for payouts
	BankAccountIban string `json:"bank_account_iban"`
	BusinessName    string `json:"business_name"`

	// Currency Currency code in ISO 4217 format
	Currency Currency `json:"currency"`

	// PlatformEntityUuid UUID of a legal entity (partner)
	PlatformEntityUuid LegalEntityUUID `json:"platform_entity_uuid"`
	TaxId              string          `json:"tax_id"`
}

// Currency Currency code in ISO 4217 format
type Currency = shared.Currency

// ErrorDetails defines model for ErrorDetails.
type ErrorDetails struct {
	EntityId   *string `json:"entity_id,omitempty"`
	EntityType *string `json:"entity_type,omitempty"`
	ErrorSlug  string  `json:"error_slug"`
	Message    string  `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Details Detailed error information
	Details []ErrorDetails `json:"details"`

	// Message Human-readable error message
	Message string `json:"message"`

	// Slug Error slug
	Slug string `json:"slug"`
}

// LegalEntityUUID UUID of a legal entity (partner)
type LegalEntityUUID = domain.LegalEntityUUID

// OnboardPartner defines model for OnboardPartner.
type OnboardPartner struct {
	Address Address `json:"address"`

	// BankAccountIban Bank account IBAN for payouts
	BankAccountIban string `json:"bank_account_iban"`

	// BusinessName Legal business name of the partner
	BusinessName string `json:"business_name"`

	// Currency Currency code in ISO 4217 format
	Currency Currency `json:"currency"`

	// PartnerType Type of partner being onboarded
	PartnerType PartnerType `json:"partner_type"`

	// PartnerUuid UUID of a legal entity (partner)
	PartnerUuid LegalEntityUUID `json:"partner_uuid"`

	// PlatformEntityUuid UUID of a platform entity
	PlatformEntityUuid PlatformEntityUUID `json:"platform_entity_uuid"`

	// TaxId Tax identification number
	TaxId string `json:"tax_id"`
}

// OperatorUUID UUID of an operator
type OperatorUUID = common.UUID

// PartnerType Type of partner being onboarded
type PartnerType = domain.PartnerType

// PlatformEntityUUID UUID of a platform entity
type PlatformEntityUUID = models.PlatformEntityUUID

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// CreatePlatformEntityParams defines parameters for CreatePlatformEntity.
type CreatePlatformEntityParams struct {
	OperatorUUID OperatorUUID `json:"Operator-UUID"`
}

// OnboardPartnerParams defines parameters for OnboardPartner.
type OnboardPartnerParams struct {
	OperatorUUID OperatorUUID `json:"Operator-UUID"`
}

// CreatePlatformEntityJSONRequestBody defines body for CreatePlatformEntity for application/json ContentType.
type CreatePlatformEntityJSONRequestBody = CreatePlatformEntity

// OnboardPartnerJSONRequestBody defines body for OnboardPartner for application/json ContentType.
type OnboardPartnerJSONRequestBody = OnboardPartner

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetBillingCyclesByPartner request
	GetBillingCyclesByPartner(ctx context.Context, partnerUuid LegalEntityUUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreatePlatformEntityWithBody request with any body
	CreatePlatformEntityWithBody(ctx context.Context, params *CreatePlatformEntityParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreatePlatformEntity(ctx context.Context, params *CreatePlatformEntityParams, body CreatePlatformEntityJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OnboardPartnerWithBody request with any body
	OnboardPartnerWithBody(ctx context.Context, params *OnboardPartnerParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	OnboardPartner(ctx context.Context, params *OnboardPartnerParams, body OnboardPartnerJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetBillingCyclesByPartner(ctx context.Context, partnerUuid LegalEntityUUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetBillingCyclesByPartnerRequest(c.Server, partnerUuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreatePlatformEntityWithBody(ctx context.Context, params *CreatePlatformEntityParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePlatformEntityRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreatePlatformEntity(ctx context.Context, params *CreatePlatformEntityParams, body CreatePlatformEntityJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePlatformEntityRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OnboardPartnerWithBody(ctx context.Context, params *OnboardPartnerParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOnboardPartnerRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OnboardPartner(ctx context.Context, params *OnboardPartnerParams, body OnboardPartnerJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOnboardPartnerRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetBillingCyclesByPartnerRequest generates requests for GetBillingCyclesByPartner
func NewGetBillingCyclesByPartnerRequest(server string, partnerUuid LegalEntityUUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "partner_uuid", runtime.ParamLocationPath, partnerUuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/settlements/billing-cycles/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreatePlatformEntityRequest calls the generic CreatePlatformEntity builder with application/json body
func NewCreatePlatformEntityRequest(server string, params *CreatePlatformEntityParams, body CreatePlatformEntityJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreatePlatformEntityRequestWithBody(server, params, "application/json", bodyReader)
}

// NewCreatePlatformEntityRequestWithBody generates requests for CreatePlatformEntity with any type of body
func NewCreatePlatformEntityRequestWithBody(server string, params *CreatePlatformEntityParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/settlements/create-platform-entity")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "Operator-UUID", runtime.ParamLocationHeader, params.OperatorUUID)
		if err != nil {
			return nil, err
		}

		req.Header.Set("Operator-UUID", headerParam0)

	}

	return req, nil
}

// NewOnboardPartnerRequest calls the generic OnboardPartner builder with application/json body
func NewOnboardPartnerRequest(server string, params *OnboardPartnerParams, body OnboardPartnerJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewOnboardPartnerRequestWithBody(server, params, "application/json", bodyReader)
}

// NewOnboardPartnerRequestWithBody generates requests for OnboardPartner with any type of body
func NewOnboardPartnerRequestWithBody(server string, params *OnboardPartnerParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/settlements/onboard-partner")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "Operator-UUID", runtime.ParamLocationHeader, params.OperatorUUID)
		if err != nil {
			return nil, err
		}

		req.Header.Set("Operator-UUID", headerParam0)

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetBillingCyclesByPartnerWithResponse request
	GetBillingCyclesByPartnerWithResponse(ctx context.Context, partnerUuid LegalEntityUUID, reqEditors ...RequestEditorFn) (*GetBillingCyclesByPartnerResponse, error)

	// CreatePlatformEntityWithBodyWithResponse request with any body
	CreatePlatformEntityWithBodyWithResponse(ctx context.Context, params *CreatePlatformEntityParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePlatformEntityResponse, error)

	CreatePlatformEntityWithResponse(ctx context.Context, params *CreatePlatformEntityParams, body CreatePlatformEntityJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePlatformEntityResponse, error)

	// OnboardPartnerWithBodyWithResponse request with any body
	OnboardPartnerWithBodyWithResponse(ctx context.Context, params *OnboardPartnerParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*OnboardPartnerResponse, error)

	OnboardPartnerWithResponse(ctx context.Context, params *OnboardPartnerParams, body OnboardPartnerJSONRequestBody, reqEditors ...RequestEditorFn) (*OnboardPartnerResponse, error)
}

type GetBillingCyclesByPartnerResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]BillingCycle
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON404      *NotFound
}

// Status returns HTTPResponse.Status
func (r GetBillingCyclesByPartnerResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetBillingCyclesByPartnerResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreatePlatformEntityResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *struct {
		// PlatformEntityUuid UUID of a platform entity
		PlatformEntityUuid PlatformEntityUUID `json:"platform_entity_uuid"`
	}
	JSON400 *BadRequest
	JSON401 *Unauthorized
}

// Status returns HTTPResponse.Status
func (r CreatePlatformEntityResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreatePlatformEntityResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type OnboardPartnerResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *BadRequest
	JSON401      *Unauthorized
}

// Status returns HTTPResponse.Status
func (r OnboardPartnerResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OnboardPartnerResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetBillingCyclesByPartnerWithResponse request returning *GetBillingCyclesByPartnerResponse
func (c *ClientWithResponses) GetBillingCyclesByPartnerWithResponse(ctx context.Context, partnerUuid LegalEntityUUID, reqEditors ...RequestEditorFn) (*GetBillingCyclesByPartnerResponse, error) {
	rsp, err := c.GetBillingCyclesByPartner(ctx, partnerUuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetBillingCyclesByPartnerResponse(rsp)
}

// CreatePlatformEntityWithBodyWithResponse request with arbitrary body returning *CreatePlatformEntityResponse
func (c *ClientWithResponses) CreatePlatformEntityWithBodyWithResponse(ctx context.Context, params *CreatePlatformEntityParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePlatformEntityResponse, error) {
	rsp, err := c.CreatePlatformEntityWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreatePlatformEntityResponse(rsp)
}

func (c *ClientWithResponses) CreatePlatformEntityWithResponse(ctx context.Context, params *CreatePlatformEntityParams, body CreatePlatformEntityJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePlatformEntityResponse, error) {
	rsp, err := c.CreatePlatformEntity(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreatePlatformEntityResponse(rsp)
}

// OnboardPartnerWithBodyWithResponse request with arbitrary body returning *OnboardPartnerResponse
func (c *ClientWithResponses) OnboardPartnerWithBodyWithResponse(ctx context.Context, params *OnboardPartnerParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*OnboardPartnerResponse, error) {
	rsp, err := c.OnboardPartnerWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOnboardPartnerResponse(rsp)
}

func (c *ClientWithResponses) OnboardPartnerWithResponse(ctx context.Context, params *OnboardPartnerParams, body OnboardPartnerJSONRequestBody, reqEditors ...RequestEditorFn) (*OnboardPartnerResponse, error) {
	rsp, err := c.OnboardPartner(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOnboardPartnerResponse(rsp)
}

// ParseGetBillingCyclesByPartnerResponse parses an HTTP response from a GetBillingCyclesByPartnerWithResponse call
func ParseGetBillingCyclesByPartnerResponse(rsp *http.Response) (*GetBillingCyclesByPartnerResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetBillingCyclesByPartnerResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []BillingCycle
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseCreatePlatformEntityResponse parses an HTTP response from a CreatePlatformEntityWithResponse call
func ParseCreatePlatformEntityResponse(rsp *http.Response) (*CreatePlatformEntityResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreatePlatformEntityResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest struct {
			// PlatformEntityUuid UUID of a platform entity
			PlatformEntityUuid PlatformEntityUUID `json:"platform_entity_uuid"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseOnboardPartnerResponse parses an HTTP response from a OnboardPartnerWithResponse call
func ParseOnboardPartnerResponse(rsp *http.Response) (*OnboardPartnerResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OnboardPartnerResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}
