# Reading List API

@baseUrl = http://localhost:4000/api/v1

### Get health check status
GET {{baseUrl}}/healthcheck

### An error if use POST method to get health check status
POST {{baseUrl}}/healthcheck