// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package http

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"eats/backend/common"
	"eats/backend/common/shared"
	"eats/backend/settlements/app/models"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
	"eats/backend/settlements/domain"
)

// Address defines model for Address.
type Address struct {
	// City City name
	City string `json:"city"`

	// CountryCode ISO 3166-1 alpha-2 country code
	CountryCode shared.CountryCode `json:"country_code"`

	// Line1 First address line
	Line1 string `json:"line1"`

	// Line2 Second address line
	Line2 string `json:"line2"`

	// PostalCode Postal code
	PostalCode string `json:"postal_code"`
}

// CreatePlatformEntity defines model for CreatePlatformEntity.
type CreatePlatformEntity struct {
	Address Address `json:"address"`

	// BankAccountIban Bank account IBAN for payouts
	BankAccountIban string `json:"bank_account_iban"`
	BusinessName    string `json:"business_name"`

	// Currency Currency code in ISO 4217 format
	Currency Currency `json:"currency"`

	// PlatformEntityUuid UUID of a legal entity (partner)
	PlatformEntityUuid LegalEntityUUID `json:"platform_entity_uuid"`
	TaxId              string          `json:"tax_id"`
}

// Currency Currency code in ISO 4217 format
type Currency = shared.Currency

// ErrorDetails defines model for ErrorDetails.
type ErrorDetails struct {
	EntityId   *string `json:"entity_id,omitempty"`
	EntityType *string `json:"entity_type,omitempty"`
	ErrorSlug  string  `json:"error_slug"`
	Message    string  `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Details Detailed error information
	Details []ErrorDetails `json:"details"`

	// Message Human-readable error message
	Message string `json:"message"`

	// Slug Error slug
	Slug string `json:"slug"`
}

// LegalEntityUUID UUID of a legal entity (partner)
type LegalEntityUUID = domain.LegalEntityUUID

// OnboardPartner defines model for OnboardPartner.
type OnboardPartner struct {
	Address Address `json:"address"`

	// BankAccountIban Bank account IBAN for payouts
	BankAccountIban string `json:"bank_account_iban"`

	// BusinessName Legal business name of the partner
	BusinessName string `json:"business_name"`

	// Currency Currency code in ISO 4217 format
	Currency Currency `json:"currency"`

	// PartnerType Type of partner being onboarded
	PartnerType PartnerType `json:"partner_type"`

	// PartnerUuid UUID of a legal entity (partner)
	PartnerUuid LegalEntityUUID `json:"partner_uuid"`

	// PlatformEntityUuid UUID of a platform entity
	PlatformEntityUuid PlatformEntityUUID `json:"platform_entity_uuid"`

	// TaxId Tax identification number
	TaxId string `json:"tax_id"`
}

// OperatorUUID UUID of an operator
type OperatorUUID = common.UUID

// PartnerType Type of partner being onboarded
type PartnerType = domain.PartnerType

// PlatformEntityUUID UUID of a platform entity
type PlatformEntityUUID = models.PlatformEntityUUID

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// CreatePlatformEntityParams defines parameters for CreatePlatformEntity.
type CreatePlatformEntityParams struct {
	OperatorUUID OperatorUUID `json:"Operator-UUID"`
}

// OnboardPartnerParams defines parameters for OnboardPartner.
type OnboardPartnerParams struct {
	OperatorUUID OperatorUUID `json:"Operator-UUID"`
}

// CreatePlatformEntityJSONRequestBody defines body for CreatePlatformEntity for application/json ContentType.
type CreatePlatformEntityJSONRequestBody = CreatePlatformEntity

// OnboardPartnerJSONRequestBody defines body for OnboardPartner for application/json ContentType.
type OnboardPartnerJSONRequestBody = OnboardPartner

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a new platform entity
	// (POST /settlements/create-platform-entity)
	CreatePlatformEntity(ctx echo.Context, params CreatePlatformEntityParams) error
	// Onboard a new partner
	// (POST /settlements/onboard-partner)
	OnboardPartner(ctx echo.Context, params OnboardPartnerParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// CreatePlatformEntity converts echo context to params.
func (w *ServerInterfaceWrapper) CreatePlatformEntity(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreatePlatformEntityParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Operator-UUID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Operator-UUID")]; found {
		var OperatorUUID OperatorUUID
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Operator-UUID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Operator-UUID", valueList[0], &OperatorUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Operator-UUID: %s", err))
		}

		params.OperatorUUID = OperatorUUID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Operator-UUID is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreatePlatformEntity(ctx, params)
	return err
}

// OnboardPartner converts echo context to params.
func (w *ServerInterfaceWrapper) OnboardPartner(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params OnboardPartnerParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Operator-UUID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Operator-UUID")]; found {
		var OperatorUUID OperatorUUID
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Operator-UUID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Operator-UUID", valueList[0], &OperatorUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Operator-UUID: %s", err))
		}

		params.OperatorUUID = OperatorUUID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Operator-UUID is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.OnboardPartner(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/settlements/create-platform-entity", wrapper.CreatePlatformEntity)
	router.POST(baseURL+"/settlements/onboard-partner", wrapper.OnboardPartner)

}

type BadRequestJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type CreatePlatformEntityRequestObject struct {
	Params CreatePlatformEntityParams
	Body   *CreatePlatformEntityJSONRequestBody
}

type CreatePlatformEntityResponseObject interface {
	VisitCreatePlatformEntityResponse(w http.ResponseWriter) error
}

type CreatePlatformEntity201JSONResponse struct {
	// PlatformEntityUuid UUID of a platform entity
	PlatformEntityUuid PlatformEntityUUID `json:"platform_entity_uuid"`
}

func (response CreatePlatformEntity201JSONResponse) VisitCreatePlatformEntityResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreatePlatformEntity400JSONResponse struct{ BadRequestJSONResponse }

func (response CreatePlatformEntity400JSONResponse) VisitCreatePlatformEntityResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreatePlatformEntity401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreatePlatformEntity401JSONResponse) VisitCreatePlatformEntityResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type OnboardPartnerRequestObject struct {
	Params OnboardPartnerParams
	Body   *OnboardPartnerJSONRequestBody
}

type OnboardPartnerResponseObject interface {
	VisitOnboardPartnerResponse(w http.ResponseWriter) error
}

type OnboardPartner204Response struct {
}

func (response OnboardPartner204Response) VisitOnboardPartnerResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type OnboardPartner400JSONResponse struct{ BadRequestJSONResponse }

func (response OnboardPartner400JSONResponse) VisitOnboardPartnerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type OnboardPartner401JSONResponse struct{ UnauthorizedJSONResponse }

func (response OnboardPartner401JSONResponse) VisitOnboardPartnerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Create a new platform entity
	// (POST /settlements/create-platform-entity)
	CreatePlatformEntity(ctx context.Context, request CreatePlatformEntityRequestObject) (CreatePlatformEntityResponseObject, error)
	// Onboard a new partner
	// (POST /settlements/onboard-partner)
	OnboardPartner(ctx context.Context, request OnboardPartnerRequestObject) (OnboardPartnerResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// CreatePlatformEntity operation middleware
func (sh *strictHandler) CreatePlatformEntity(ctx echo.Context, params CreatePlatformEntityParams) error {
	var request CreatePlatformEntityRequestObject

	request.Params = params

	var body CreatePlatformEntityJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePlatformEntity(ctx.Request().Context(), request.(CreatePlatformEntityRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePlatformEntity")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreatePlatformEntityResponseObject); ok {
		return validResponse.VisitCreatePlatformEntityResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// OnboardPartner operation middleware
func (sh *strictHandler) OnboardPartner(ctx echo.Context, params OnboardPartnerParams) error {
	var request OnboardPartnerRequestObject

	request.Params = params

	var body OnboardPartnerJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.OnboardPartner(ctx.Request().Context(), request.(OnboardPartnerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "OnboardPartner")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(OnboardPartnerResponseObject); ok {
		return validResponse.VisitOnboardPartnerResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
